### ISSUE TITLE
[syncfusion_flutter_pdf] Null check operator used on a null value (Digital sign)

### ISSUE THREAD

**Issue by stMerlHin** [syncfusion/flutter-widgets#1011]
I try to sign a pdf with the sample code on the readme.
Am using `syncfusion_flutter_pdf 20.4.38`
This is the code.
```dart
PdfDocument document = PdfDocument();

//Adds a new page
    PdfPage page = document.pages.add();

//Creates a digital signature and sets signature information
    PdfSignatureField field = PdfSignatureField(page, 'signature',
        bounds: Rect.fromLTWH(0, 0, 200, 100),
        signature: PdfSignature(
          //Creates a certificate instance from the PFX file with a private key
            certificate:
            PdfCertificate(File('cert.pfx').readAsBytesSync(), 'password123'),
            contactInfo: 'johndoe@owned.us',
            locationInfo: 'Honolulu, Hawaii',
            reason: 'I am author of this document.',
            digestAlgorithm: DigestAlgorithm.sha256,
            cryptographicStandard: CryptographicStandard.cms));

//Add a signature field to the form
    document.form.fields.add(field);

//Save and dispose the PDF document
    File('/home/st/Documents/SingOutput.pdf').writeAsBytes(await document.save());
    document.dispose();
```

And here is the excetion I got

```
Unhandled Exception: Null check operator used on a null value
#0      _PasswordUtility.createEncoder (package:syncfusion_flutter_pdf/src/pdf/implementation/security/digital_signature/pdf_pkcs_certificate.dart:739:20)
#1      _PasswordUtility.createEncoder (package:syncfusion_flutter_pdf/src/pdf/implementation/security/digital_signature/pdf_pkcs_certificate.dart:726:16)
#2      PdfPKCSCertificate.getCryptographicData (package:syncfusion_flutter_pdf/src/pdf/implementation/security/digital_signature/pdf_pkcs_certificate.dart:376:17)
#3      PdfPKCSCertificate._loadCertificate.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/security/digital_signature/pdf_pkcs_certificate.dart:175:37)
#4      List.forEach (dart:core-patch/growable_array.dart:416:8)
#5      PdfPKCSCertificate._loadCertificate (package:syncfusion_flutter_pdf/src/pdf/implementation/security/digital_signature/pdf_pkcs_certificate.dart:65:26)
#6      new PdfPKCSCertificate (package:syncfusion_flutter_pdf/src/pdf/implementation/security/digital_signature/pdf_pkcs_certificate.dart:34:5)
#7      PdfCertificate._initializeCertificate (package:syncfusion_flutter_pdf/src/pdf/implementation/security/digital_signature/pdf_certificate.dart:43:24)
#8      new PdfCertificate (package:syncfusion_flutter_pdf/src/pdf/implementation/security/digital_signature/pdf_certificate.dart:8:5)
#9      PointCategoryProvider.sign (package:know_desktop/src/provider/point_category_provider.dart:123:13)
```

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
