### ISSUE TITLE
[syncfusion_flutter_charts] trackball issue and exceptions in the LineSeries chart

### ISSUE THREAD

**Issue by ekuleshov** [syncfusion/flutter-widgets#1070]
I'm using a customized LineSeries chart for one of my personal projects. All series starts at 0, but may have different number of data points for X axis. The line chart renders fine, but the customized trackball fail to render multiple floating points when `TrackballBehavior.showByIndex(..)` is used.

I replicated this issue using a modified variant of the [chart_with_trackball.dart](https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/user_interactions/trackball/chart_with_trackball.dart) from Syncfusion Flutter demo app. You can find mu code at https://github.com/ekuleshov/sf-flutter-examples/tree/trackball_issue in the `trackball_issue` branch. All changes are in commit [5a96bf44eee5e9cd990dafcbec6773e0eb83be00](https://github.com/ekuleshov/sf-flutter-examples/commit/5a96bf44eee5e9cd990dafcbec6773e0eb83be00).

Here is the video of the issue and the error stacktrace is below. Could you please advise how to get around this issue.

https://user-images.githubusercontent.com/440954/216834047-ae6f3f80-93cd-4ea1-907b-4c964f31b5c7.mov

```
======== Exception caught by rendering library =====================================================
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  SfCartesianChart SfCartesianChart:file:///Users/eu/Documents/Projects/sf-flutter-examples/lib/samples/chart/cartesian_charts/user_interactions/trackball/chart_with_trackball.dart:414:12
When the exception was thrown, this was the stack: 
#0      TrackballTemplateRenderBox.paint (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball_template.dart:580:68)
#1      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#2      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#3      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#4      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#5      RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#8      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#9      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#10     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#13     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#14     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#15     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#21     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#22     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#23     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#27     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#31     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#37     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#40     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#43     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#49     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#50     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#53     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:338:15)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#56     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#59     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:338:15)
#60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#62     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#63     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1089:7)
#64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#66     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#69     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#72     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#73     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#74     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#75     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#76     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#77     _ChartContainerBox.paint (package:syncfusion_flutter_charts/src/common/common.dart:45:11)
#78     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#79     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#80     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#81     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#82     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#83     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#84     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1137:31)
#85     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:518:19)
#86     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#87     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#88     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#89     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#90     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#91     _invoke (dart:ui/hooks.dart:145:13)
#92     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#93     _drawFrame (dart:ui/hooks.dart:112:31)
The following RenderObject was being processed when the exception was fired: TrackballTemplateRenderBox#a7343 relayoutBoundary=up5
...  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=1233.0, 0.0<=h<=276.0)
...  size: Size(34.0, 20.0)
RenderObject: TrackballTemplateRenderBox#a7343 relayoutBoundary=up5
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=1233.0, 0.0<=h<=276.0)
  size: Size(34.0, 20.0)
...  child: _RenderColoredBox#9b66e relayoutBoundary=up6 NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(0.0<=w<=1233.0, 0.0<=h<=276.0)
...    size: Size(34.0, 20.0)
...    behavior: opaque
...    child: RenderPadding#5569d relayoutBoundary=up7 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=1233.0, 0.0<=h<=276.0)
...      size: Size(34.0, 20.0)
...      padding: EdgeInsets(8.0, 2.0, 8.0, 2.0)
...      textDirection: ltr
...      child: RenderParagraph#fe782 relayoutBoundary=up8 NEEDS-PAINT
...        parentData: offset=Offset(8.0, 2.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=1217.0, 0.0<=h<=272.0)
...        size: Size(18.0, 16.0)
...        textAlign: start
...        textDirection: ltr
...        softWrap: wrapping at box width
...        overflow: clip
...        locale: en_US
...        maxLines: unlimited
...        text: TextSpan
...          debugLabel: ((englishLike bodyMedium 2014).merge(blackRedwoodCity bodyMedium)).merge(unknown)
...          inherit: false
...          color: Color(0xffffffff)
...          family: .AppleSystemUIFont
...          size: 14.0
...          weight: 400
...          baseline: alphabetic
...          decoration: TextDecoration.none
...          "24"

```

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue regarding getting range error exceptions while using the trackball with tooltip display mode as floatAllPoints in LineSeries has been fixed and rolled out in our weekly patch release. To avoid this please upgrade the charts package to the below version.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.4.51
