### ISSUE TITLE
pdfviewer: CanvasRenderBox does not implement computeDryLayout

### ISSUE THREAD

**Issue by Leadrive** [syncfusion/flutter-widgets#113]
run the pdfviewer example, report this error.
all is the latest version.

**Comment by dillibabun** [comment]
Hi @Leadrive 

Greetings from Syncfusion.

We are unable to reproduce the reported error with the given information. Kindly share us the issue reproducing procedure with complete error log and flutter doctor output(to known your flutter version) which will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Dilli babu.

**Comment by robinbonnes** [comment]
Same issue here.

Widget:
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

class PdfViewer extends StatelessWidget {
  final String pdfPath;
  PdfViewer({required this.pdfPath});

  @override
  Widget build(BuildContext context) {
    print(pdfPath);
    return Scaffold(
      appBar: AppBar(
        title: Text("Show PDF")
      ),
      body: Container(
        child: SfPdfViewer.network(
          pdfPath,
        ),
      ),
    );
  }
}
```

Stacktrace:

```

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performResize():
The CanvasRenderBox class does not implement "computeDryLayout".


If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  SfPdfViewer file:///C:/app/lib/components/pdfviewer.dart:19:28
When the exception was thrown, this was the stack: 
#0      RenderBox.debugCannotComputeDryLayout.<anonymous closure> (package:flutter/src/rendering/box.dart:1898:9)
#1      RenderBox.debugCannotComputeDryLayout (package:flutter/src/rendering/box.dart:1902:6)
#2      RenderBox.computeDryLayout (package:flutter/src/rendering/box.dart:1858:12)
#3      RenderBox.performResize (package:flutter/src/rendering/box.dart:2321:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1756:9)
...
The following RenderObject was being processed when the exception was fired: CanvasRenderBox#1dc2c NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=411.4)
...  size: MISSING
RenderObject: CanvasRenderBox#1dc2c NEEDS-PAINT
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=411.4)
  size: MISSING
====================================================================================================
I/flutter (22352): [error] Error while capturing event with id: bb1b48eaa6a740d68f14b1d2ed54b3f9

======== Exception caught by rendering library =====================================================
RenderBox did not set its size during layout.
The relevant error-causing widget was: 
  SfPdfViewer file:///C:/app/lib/components/pdfviewer.dart:19:28
====================================================================================================
I/flutter (22352): [error] Error while capturing event with id: 91dd1baa9b844cc880b81219d2af3d69
I/flutter (22352): [error] Error while capturing event with id: 5dafc3750b924d858302941bad6b7bb9

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: CanvasRenderBox#1dc2c NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1920 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SfPdfViewer file:///C:/apps/timeking/lib/components/pdfviewer.dart:19:28
The following RenderObject was being processed when the exception was fired: RenderConstrainedBox#998c5 relayoutBoundary=up22 NEEDS-PAINT
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  size: MISSING
  additionalConstraints: BoxConstraints(w=411.4, h=411.4)
  child: CanvasRenderBox#1dc2c NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=411.4, h=411.4)
    size: MISSING
RenderObject: RenderConstrainedBox#998c5 relayoutBoundary=up22 NEEDS-PAINT
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  size: MISSING
  additionalConstraints: BoxConstraints(w=411.4, h=411.4)
  child: CanvasRenderBox#1dc2c NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=411.4, h=411.4)
    size: MISSING
```

Flutter doctor:

```
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.25.0-8.3.pre at C:\sdk\flutter
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\sdk\android-sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\sdk\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • HD1913 (mobile) • c6eb637c • android-arm64  • Android 10 (API 29)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!
```

**Comment by tlueder** [comment]
@dillibabun @robinbonnes I had the same issue and it turns oit you have to be on the stable channel for this plugin to work.
If you are on beta or dev your app won't run.

**Comment by robinbonnes** [comment]
Migrated my code to make it null-safe, so can't revert back to stable channel. Any plans to make this widget compatible with the Flutter beta channel?

**Comment by dillibabun** [comment]
@tlueder @robinbonnes  We have resolved this issue and the changes will be reflected in our upcoming weekly release which is estimated to be available by 16 February 2020 tentatively.

**Comment by dillibabun** [comment]
@tlueder  @robinbonnes - the latest package available here - https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/18.4.43-beta Kindly let us know if you have any issues.
