### ISSUE TITLE
[syncfusion_flutter_charts] Null check operator used on a null value when load more

### ISSUE THREAD

**Issue by andriescheng** [syncfusion/flutter-widgets#1139]
I copy the 'SfCartesianChart lazily load more data to the chart sample' from [thisUrl](https://www.syncfusion.com/kb/12535/how-to-lazily-load-more-data-to-the-chart-sfcartesianchart?_ga=2.38318308.679806967.1679277213-695891589.1669887677&_gl=1*16p2byk*_ga*Njk1ODkxNTg5LjE2Njk4ODc2Nzc.*_ga_WC4JKKPHH0*MTY3OTQ1NTg4Mi41NC4xLjE2Nzk0NTY1NzIuNDAuMC4w) And add one ColumnSeries and Enable Legend. When I tap the second legend to set second Series visibility to false, then scrolling to end and trigger load more function, 'Null check operator used on a null value' will show.

This is my code
```
 class ColumnChart extends StatefulWidget {
  const ColumnChart({super.key});

  @override
  State<ColumnChart> createState() => _ColumnChartState();
}

class _ColumnChartState extends State<ColumnChart> {
  _ColumnChartState();
  ChartSeriesController? seriesController;
  late List<ChartSampleData> chartData;

  late bool isLoadMoreView, isNeedToUpdateView, isDataUpdated;

  double? oldAxisVisibleMin, oldAxisVisibleMax;

  late ZoomPanBehavior _zoomPanBehavior;

  late GlobalKey<State> globalKey;
  @override
  void initState() {
    _initializeVariables();
    super.initState();
  }

  @override
  void didUpdateWidget(oldWidget) {
    super.didUpdateWidget(oldWidget);
  }

  void _initializeVariables() {
    chartData = <ChartSampleData>[
      ChartSampleData(xValue: 0, y: 326, volume: 242),
      ChartSampleData(xValue: 1, y: 416, volume: 242),
      ChartSampleData(xValue: 2, y: 290, volume: 242),
      ChartSampleData(xValue: 3, y: 70, volume: 242),
      ChartSampleData(xValue: 4, y: 500, volume: 242),
      ChartSampleData(xValue: 5, y: 416, volume: 242),
      ChartSampleData(xValue: 6, y: 290, volume: 242),
      ChartSampleData(xValue: 7, y: 120, volume: 242),
      ChartSampleData(xValue: 8, y: 500, volume: 242),
    ];
    isLoadMoreView = false;
    isNeedToUpdateView = false;
    isDataUpdated = true;
    globalKey = GlobalKey<State>();
    _zoomPanBehavior = ZoomPanBehavior(
      enablePinching: true,
      zoomMode: ZoomMode.x,
      enablePanning: true,
    );
  }

  @override
  Widget build(BuildContext context) {
    return _buildInfiniteScrollingChart();
  }

  /// Returns the cartesian chart with default trackball.
  SfCartesianChart _buildInfiniteScrollingChart() {
    return SfCartesianChart(
      key: GlobalKey<State>(),
      onActualRangeChanged: (ActualRangeChangedArgs args) {
        if (args.orientation == AxisOrientation.horizontal) {
          if (isLoadMoreView) {
            args.visibleMin = oldAxisVisibleMin;
            args.visibleMax = oldAxisVisibleMax;
          }
          oldAxisVisibleMin = args.visibleMin as double;
          oldAxisVisibleMax = args.visibleMax as double;
        }
        isLoadMoreView = false;
      },
      zoomPanBehavior: _zoomPanBehavior,
      plotAreaBorderWidth: 0,
      primaryXAxis: NumericAxis(
          name: 'XAxis',
          interval: 2,
          enableAutoIntervalOnZooming: false,
          edgeLabelPlacement: EdgeLabelPlacement.shift,
          majorGridLines: const MajorGridLines(width: 0),
          axisLabelFormatter: (AxisLabelRenderDetails details) {
            return ChartAxisLabel(details.text.split('.')[0], null);
          }),
      primaryYAxis: NumericAxis(
          axisLine: const AxisLine(width: 0),
          majorTickLines: const MajorTickLines(color: Colors.transparent),
          axisLabelFormatter: (AxisLabelRenderDetails details) {
            return ChartAxisLabel(details.text, null);
          }),
      series: getSeries(),
      loadMoreIndicatorBuilder:
          (BuildContext context, ChartSwipeDirection direction) =>
              getloadMoreIndicatorBuilder(context, direction),
      legend: Legend(
        isVisible: true,
        position: LegendPosition.top,
        overflowMode: LegendItemOverflowMode.wrap,
      ),
    );
  }

  List<ChartSeries<ChartSampleData, num>> getSeries() {
    return <ChartSeries<ChartSampleData, num>>[
      ColumnSeries<ChartSampleData, num>(
          dataSource: chartData,
          color: const Color.fromRGBO(75, 135, 185, 0.6),
          borderColor: const Color.fromRGBO(75, 135, 185, 1),
          borderWidth: 2,
          xValueMapper: (ChartSampleData sales, _) => sales.xValue as num,
          yValueMapper: (ChartSampleData sales, _) => sales.y,
          onRendererCreated: (ChartSeriesController controller) {
            seriesController = controller;
          },
          name: 'a',
          dataLabelSettings: const DataLabelSettings(
              isVisible: true,
              labelAlignment: ChartDataLabelAlignment.top,
              textStyle: TextStyle(fontSize: 10, color: Colors.white))),
      ColumnSeries<ChartSampleData, num>(
          dataSource: chartData,
          color: const Color.fromRGBO(75, 135, 185, 0.6),
          borderColor: const Color.fromRGBO(75, 135, 185, 1),
          borderWidth: 2,
          xValueMapper: (ChartSampleData sales, _) => sales.xValue as num,
          yValueMapper: (ChartSampleData sales, _) => sales.volume,
          onRendererCreated: (ChartSeriesController controller) {
            seriesController = controller;
          },
          name: 'b',
          dataLabelSettings: const DataLabelSettings(
              isVisible: true,
              labelAlignment: ChartDataLabelAlignment.top,
              textStyle: TextStyle(fontSize: 10, color: Colors.white))),
    ];
  }

  Widget getloadMoreIndicatorBuilder(
      BuildContext context, ChartSwipeDirection direction) {
    if (direction == ChartSwipeDirection.end) {
      isNeedToUpdateView = true;
      globalKey = GlobalKey<State>();
      return StatefulBuilder(
          key: globalKey,
          builder: (BuildContext context, StateSetter stateSetter) {
            Widget widget;
            if (isNeedToUpdateView) {
              widget = getProgressIndicator();
              _updateView();
              isDataUpdated = true;
            } else {
              widget = Container();
            }
            return widget;
          });
    } else {
      return SizedBox.fromSize(size: Size.zero);
    }
  }

  Widget getProgressIndicator() {
    return Align(
        alignment: Alignment.centerRight,
        child: Padding(
            padding: const EdgeInsets.only(bottom: 22),
            child: Container(
                width: 50,
                alignment: Alignment.centerRight,
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                      colors: Colors.red == Brightness.light
                          ? <Color>[
                              Colors.white.withOpacity(0.0),
                              Colors.white.withOpacity(0.74)
                            ]
                          : const <Color>[
                              Color.fromRGBO(33, 33, 33, 0.0),
                              Color.fromRGBO(33, 33, 33, 0.74)
                            ],
                      stops: const <double>[0.0, 1]),
                ),
                child: SizedBox(
                    height: 35,
                    width: 35,
                    child: CircularProgressIndicator(
                      valueColor:
                          AlwaysStoppedAnimation<Color>(Colors.lightBlue),
                      backgroundColor: Colors.transparent,
                      strokeWidth: 3,
                    )))));
  }

  void _updateData() {
    for (int i = 0; i < 4; i++) {
      chartData.add(ChartSampleData(
          xValue: chartData[chartData.length - 1].xValue + 1,
          y: getRandomInt(0, 600),
          volume: getRandomInt(0, 600)));
    }
    isLoadMoreView = true;
    seriesController?.updateDataSource(addedDataIndexes: getIndexes(4));

    print('test');
  }

  Future<void> _updateView() async {
    await Future<void>.delayed(const Duration(seconds: 1), () {
      isNeedToUpdateView = false;
      if (isDataUpdated) {
        _updateData();
        isDataUpdated = false;
      }
      if (globalKey.currentState != null) {
        (globalKey.currentState as dynamic).setState(() {});
      }
    });
  }

  List<int> getIndexes(int length) {
    final List<int> indexes = <int>[];
    for (int i = length - 1; i >= 0; i--) {
      indexes.add(chartData.length - 1 - i);
    }
    return indexes;
  }

  int getRandomInt(int min, int max) {
    final Random random = Random();
    final int result = min + random.nextInt(max - min);
    return result < 50 ? 95 : result;
  }

  @override
  void dispose() {
    seriesController = null;
    super.dispose();
  }
}

//Chart sample data
class ChartSampleData {
  /// Holds the datapoint values like x, y, etc.,
  ChartSampleData(
      {this.x,
      this.y,
      this.xValue,
      this.yValue,
      this.secondSeriesYValue,
      this.thirdSeriesYValue,
      this.pointColor,
      this.size,
      this.text,
      this.open,
      this.close,
      this.low,
      this.high,
      this.volume});

  /// Holds x value of the datapoint
  final dynamic x;

  /// Holds y value of the datapoint
  final num? y;

  /// Holds x value of the datapoint
  final dynamic xValue;

  /// Holds y value of the datapoint
  final num? yValue;

  /// Holds y value of the datapoint(for 2nd series)
  final num? secondSeriesYValue;

  /// Holds y value of the datapoint(for 3nd series)
  final num? thirdSeriesYValue;

  /// Holds point color of the datapoint
  final Color? pointColor;

  /// Holds size of the datapoint
  final num? size;

  /// Holds datalabel/text value mapper of the datapoint
  final String? text;

  /// Holds open value of the datapoint
  final num? open;

  /// Holds close value of the datapoint
  final num? close;

  /// Holds low value of the datapoint
  final num? low;

  /// Holds high value of the datapoint
  final num? high;

  /// Holds open value of the datapoint
  final num? volume;
}
```

StackTrace:
```
#0      ChartSeriesController._addOrUpdateDataPoint (package:syncfusion_flutter_charts/src/chart/chart_series/series.dart:1364:43)
#1      ChartSeriesController._addOrUpdateDataPoints (package:syncfusion_flutter_charts/src/chart/chart_series/series.dart:1307:7)
#2      ChartSeriesController.updateDataSource (package:syncfusion_flutter_charts/src/chart/chart_series/series.dart:1288:7)
#3      _ColumnChartState._updateData (package:jedi_ma/features/dashboard/widgets/chart/column_chart.dart:210:23)
#4      _ColumnChartState._updateView.<anonymous closure> (package:jedi_ma/features/dashboard/widgets/chart/column_chart.dart:219:9)
#5      new Future.delayed.<anonymous closure> (dart:async/future.dart:424:39)
#6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

```

![image](https://user-images.githubusercontent.com/128566492/226799373-a2d74ac8-73e4-4edb-b10b-1e7845c9bd6c.png)

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked your code snippet, and we have created a workaround to overcome this issue by maintaining the list that contains the series visibility, then we have changed the series visibility based on the legend tap with the help of the [onLegenTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onLegendTapped.html) callback. Then checked whether the series visibility is true and then called the [updataDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method for the respective series otherwise ignored it. We have shared the sample below for your reference.

Sample: 
[i449418.zip](https://github.com/syncfusion/flutter-widgets/files/11078704/i449418.zip)
