### ISSUE TITLE
Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException

### ISSUE THREAD

**Issue by harsh8088** [syncfusion/flutter-widgets#1394]
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): Failed to handle method call
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): java.lang.NullPointerException
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at java.util.Objects.requireNonNull(Objects.java:220)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.closeDocument(SyncfusionFlutterPdfViewerPlugin.java:229)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.onMethodCall(SyncfusionFlutterPdfViewerPlugin.java:99)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(Unknown Source:12)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#syncfusion_flutter_pdfviewer(24939): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (24939): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (24939): 	at java.util.Objects.requireNonNull(Objects.java:220)
E/flutter (24939): 	at com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.closeDocument(SyncfusionFlutterPdfViewerPlugin.java:229)
E/flutter (24939): 	at com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.onMethodCall(SyncfusionFlutterPdfViewerPlugin.java:99)
E/flutter (24939): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (24939): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (24939): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/flutter (24939): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(Unknown Source:12)
E/flutter (24939): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (24939): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (24939): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (24939): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (24939): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter (24939): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (24939): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (24939): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (24939): )
E/flutter (24939): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (24939): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (24939): <asynchronous suspension>
E/flutter (24939): #2      PdfViewerPlugin.closeDocument (package:syncfusion_flutter_pdfviewer/src/common/pdfviewer_plugin.dart:154:7)
E/flutter (24939): <asynchronous suspension>
E/flutter (24939): 
E/FlutterJNI(24939): Failed to decode image
E/FlutterJNI(24939): android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
E/FlutterJNI(24939): 	at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(24939): 	at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI(24939): 	at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:251)
E/FlutterJNI(24939): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1935)
E/FlutterJNI(24939): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1927)
E/FlutterJNI(24939): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:538)
E/flutter (24939): [ERROR:flutter/runtime/dart_isolate.cc(1097)] Unhandled exception:
E/flutter (24939): type 'Null' is not a subtype of type 'num'
E/flutter (24939): #0      SfPdfViewerState._extractTextAsync (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:1704:40)
E/flutter (24939): <asynchronous suspension>

//CODE 

  @override
  Widget build(BuildContext context) {
    print('DOC.URL:${widget.url}');
    return Scaffold(
      appBar: AppBar(
        title: Center(
            child: Image.asset('assets/images/ic_app_logo_new.png',
                height: 40, fit: BoxFit.cover)),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black54,
        actions: <Widget>[
          Visibility(
            visible: false,
            maintainSize: true,
            maintainAnimation: true,
            maintainSemantics: true,
            maintainState: true,
            maintainInteractivity: true,
            child: NamedIcon(
              key: Key("noti_key"),
              text: '',
              iconData: Icons.notifications_outlined,
              notificationCount: 3,
              onTap: () {
                // Navigator.pushNamed(context, "/notifications");
              },
            ),
          ),
        ],
      ),
      body: isPdf
          ? SfPdfViewer.network(
              '${widget.url}',
              // key: _pdfViewerKey,
              onDocumentLoadFailed: (details) {
                print(details.toString());
                setState(() {
                  isPdf = false;
                });
              },
            )
          : Container(
              color: Colors.transparent,
              alignment: Alignment.topCenter,
              child: Center(
                child: InteractiveViewer(
                  minScale: 0.1,
                  maxScale: 6,
                  child: Image.network('${widget.url}',
                      errorBuilder: (context, error, stackTrace) {
                    return Container(
                      alignment: Alignment.center,
                      child: Image.asset('assets/images/ic_attachment.png',
                          height: 40, fit: BoxFit.cover),
                    );
                  }),
                ),
              ),
            ),
    );
  }

**Comment by immankumarsync** [comment]
@harsh8088, To load a PDF from a network location using SfPdfViewer.network in Android on Release mode, network permission must be enabled for the application. This can be done by adding the following line in the `[flutter-app]\android\app\src\main\AndroidManifest.xml` file:
`<uses-permission android:name="android.permission.INTERNET"/>`

We were unable to replicate the reported issue (Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException), and we suspect that the issue might be related to a specific document. Kindly share the PDF document or a similar one in which you are facing this issue. This will be helpful for us to provide a prompt solution at the earliest.

**Comment by harsh8088** [comment]
> @harsh8088, To load a PDF from a network location using SfPdfViewer.network in Android on Release mode, network permission must be enabled for the application. This can be done by adding the following line in the `[flutter-app]\android\app\src\main\AndroidManifest.xml` file: `<uses-permission android:name="android.permission.INTERNET"/>`
> 
> We were unable to replicate the reported issue (Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException), and we suspect that the issue might be related to a specific document. Kindly share the PDF document or a similar one in which you are facing this issue. This will be helpful for us to provide a prompt solution at the earliest.

Please check these PDF URLs:
<img width="863" alt="Screenshot 2023-09-12 at 5 48 08 PM" src="https://github.com/syncfusion/flutter-widgets/assets/7496696/9ea7da1a-1bee-42bc-bc54-2a835a9c1731">

[https://qb-innocirc-backups.s3.ap-south-1.amazonaws.com/Pre-Prod/1/document/2023/9/13/f6dc5069-4870-4c9b-9f65-8e6bdf9b2976.pdf](url)
[https://www.africau.edu/images/default/sample.pdf](url)

**Comment by immankumarsync** [comment]
@harsh8088, Both the PDF documents from the URL are loading perfectly with `SfPdfViewer.netwrok` in both Android and iOS devices in release mode.
[SfPdfViewer.network.zip](https://github.com/syncfusion/flutter-widgets/files/12607754/SfPdfViewer.network.zip)
The attachment contains the sample we used and the screenshots from Android and iOS devices.
We have checked this with Realme 5 pro and iPad 5th generation devices.

**Comment by harsh8088** [comment]
@immankumarsync 
**Steps to Reproduce this Issue**
1:  We are uploading the pdf file to the server. 

2:  After uploading we clear the cache Directory.

<img width="734" alt="Screenshot 2023-09-15 at 12 03 10 PM" src="https://github.com/syncfusion/flutter-widgets/assets/7496696/a8a6870d-c87a-4f50-983e-7bac346dc25a">

3:  Then the PDF URL is not loading in SfPdfViewer.network() widget.

**Note: Without Step 2, SfPdfViewer is working fine.**

**Comment by deepika134** [comment]
We tried to replicate the reported issue with provided details, but PDF is loaded properly after clear the cache on our side. For your reference, we have attached the sample and included a screen recording of the output, which can be downloaded from the attachment. Please review the shared sample. If the issue still occurs on your end, kindly share the modified issue replicating sample. This will be helpful for us to provide prompt solution at earliest.
[Sample.zip](https://github.com/syncfusion/flutter-widgets/files/12805349/Sample.zip)

**Comment by ramkumarsync** [comment]
We are closing this issue since we don't have enough information to reproduce it. You can reopen this anytime and share the requested details to proceed further.
