### ISSUE TITLE
datagrid_widget selection manager is missing mounted check

### ISSUE THREAD

**Issue by ekuleshov** [syncfusion/flutter-widgets#1442]
I'm getting a lots of null check exceptions from the `datagrid_widget` 23.1.38. See stack trace below.

It seems like the `_handleSelectionController` (a listener registered in the `initState()` method) does not check if the widget's state  is still `mounted` when it calls `setState()`.

Also the `_handleSelectionController` is not being unregistered in the `dispose()` method of the `_ScrollViewWidgetState`.

```
Null check operator used on a null value
 #0 State.setState (package:flutter/src/widgets/framework.dart:1158)
 #1 _ScrollViewWidgetState._handleSelectionController (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:720)
 #2 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403)
 #3 RowSelectionManager._applySelection (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:193) 
 #4 RowSelectionManager._processSelection (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:598) 
#5 RowSelectionManager.handleTap (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:568) 
#6 DataCellBase.onTouchUp (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/generator.dart:104) 
#7 _handleOnTapUp (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/cell_widget.dart:2709) 
#8 _GridCellState._handleDoubleTapOnEditing.<anonymous closure> (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/cell_widget.dart:97) 
#9 _rootRun (dart:async/zone.dart:1391) 
#10 _CustomZone.run (dart:async/zone.dart:1301) 
#11 _CustomZone.runGuarded (dart:async/zone.dart:1209) 
#12 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249) 
#13 _rootRun (dart:async/zone.dart:1399) 
#14 _CustomZone.run (dart:async/zone.dart:1301) 
#15 _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233) 
#16 Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18) 
#17 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398) 
#18 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429) 
#19 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ekuleshov,

Thank you for bringing this to our attention. We will proceed to unregister the `_handleSelectionController` in the `dispose()` method of the `_ScrollViewWidgetState`. 

Regarding the null-check exception, could you please provide us with the steps to reproduce the issue? Having these steps will allow us to effectively investigate the problem on our end and ensure that we address it comprehensively, including other related cases. Your assistance in providing these steps is greatly appreciated.

Regards,
Tamilarasan

**Comment by ekuleshov** [comment]
> Regarding the null-check exception, could you please provide us with the steps to reproduce the issue? Having these steps will allow us to effectively investigate the problem on our end and ensure that we address it comprehensively, including other related cases. Your assistance in providing these steps is greatly appreciated.

@Tamilarasan-Paranthaman thank you for getting back to me on this. Unfortunately this crash is happening on the user's devices and I only getting the Crashlytics report without much details or context, so I can't really provide an isolated example that would allow to reproduce issue.

However if you look at the stack trace in my report above. You can see that the `setState()` call from the `_ScrollViewWidgetState._handleSelectionController()` method is called from an async chain triggered by `Timer`, but it is not checking if the current `BuildContext` is still mounted.

I think you simply need to wrap the `setState()` call in the following `_ScrollViewWidgetState._handleSelectionController()` with `if(mounted)` check. Also see https://dart.dev/tools/linter-rules/use_build_context_synchronously

https://github.com/syncfusion/flutter-widgets/blob/286835a8653bcf50e0af41141a3ee1218acb9a9a/packages/syncfusion_flutter_datagrid/lib/src/datagrid_widget/widgets/scrollview_widget.dart#L719-L723

**Comment by Tamilarasan-Paranthaman** [comment]
@ekuleshov, we are pleased to inform you that we have promptly resolved this matter in our most recent DataGrid version. To ensure you benefit from this fix, we kindly request that you update the **syncfusion_flutter_datagrid** package to version **23.1.44**.

**Comment by FarjanaParveen** [comment]
Hi @ekuleshov ,

We are suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards,
Farjana Parveen A
