### ISSUE TITLE
Unhandled Exception: Invalid argument (The character is not supported by the font.): 55324

### ISSUE THREAD

**Issue by matifdeveloper** [syncfusion/flutter-widgets#1469]
```
E/flutter ( 5001): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument (The character is not supported by the font.): 55324
E/flutter ( 5001): #0      StandardWidthTable._returnValue (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_font_metrics.dart:115:7)
E/flutter ( 5001): #1      StandardWidthTable.[] (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_font_metrics.dart:112:34)
E/flutter ( 5001): #2      PdfStandardFontHelper.getCharWidthInternal (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_standard_font.dart:436:62)
E/flutter ( 5001): #3      PdfStandardFontHelper.getLineWidth (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_standard_font.dart:452:32)
E/flutter ( 5001): #4      PdfFontHelper.getLineWidth (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_font.dart:286:52)
E/flutter ( 5001): #5      PdfStringLayouter._getLineWidth (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_string_layouter.dart:261:26)
E/flutter ( 5001): #6      PdfStringLayouter._layoutLine (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_string_layouter.dart:114:24)
E/flutter ( 5001): #7      PdfStringLayouter._doLayout (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_string_layouter.dart:57:20)
E/flutter ( 5001): #8      PdfStringLayouter.layout (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/fonts/pdf_string_layouter.dart:45:42)
E/flutter ( 5001): #9      PdfGridCellHelper.measureHeight (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid_cell.dart:822:53)
E/flutter ( 5001): #10     PdfGridCell.height (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid_cell.dart:264:25)
E/flutter ( 5001): #11     PdfGridRow._measureHeight (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid_row.dart:282:60)
E/flutter ( 5001): #12     PdfGridRow.height (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid_row.dart:243:17)
E/flutter ( 5001): #13     PdfGridLayouter._drawRow (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/layouting/pdf_grid_layouter.dart:1047:17)
E/flutter ( 5001): #14     PdfGridLayouter._layoutOnPage (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/layouting/pdf_grid_layouter.dart:325:38)
E/flutter ( 5001): #15     PdfGridLayouter.layoutInternal (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/layouting/pdf_grid_layouter.dart:1815:12)
E/flutter ( 5001): #16     PdfGridHelper.layout (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid.dart:3852:34)
E/flutter ( 5001): #17     PdfLayoutElementHelper.layout (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/figures/base/layout_element.dart:108:55)
E/flutter ( 5001): #18     PdfLayoutElement._draw (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/figures/base/layout_element.dart:51:22)
E/flutter ( 5001): #19     PdfLayoutElement.draw (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/figures/base/layout_element.dart:38:12)
E/flutter ( 5001): #20     PdfGrid.draw (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid.dart:546:17)
E/flutter ( 5001): #21     PDFServices.exportChats (package:ai_chat/services/core_functionalities/pdf_services.dart:106:10)
E/flutter ( 5001): <asynchronous suspension>
E/flutter ( 5001): 

```

**Comment by rostopira** [comment]
Same issue here, but it says character 8290 is unsupported.
I've checked my strings, and the only non ASCII character I have is 8322 in string `H₂S`.
And it's definitely supported by the TTF that I use, I've double checked that.

**Comment by matifdeveloper** [comment]
> Same issue here, but it says character 8290 is unsupported. I've checked my strings, and the only non ASCII character I have is 8322 in string `H₂S`. And it's definitely supported by the TTF that I use, I've double checked that.
> 
> I'm using `syncfusion_flutter_pdf: 22.2.12`
> 
> It's only happening, when this text is used inside table. When using drawString same string is drawn just fine.

use printing: ^5.11.0
```
final emoji = await PdfGoogleFonts.notoColorEmoji();

pdf.addPage(pw.Page(
    pageFormat: PdfPageFormat.a4,
    build: (pw.Context context) {
      return pw.Center(
        child: pw.Text(
          'Hello 🐒💁👌🎍😍🦊👨 world!',
          style: pw.TextStyle(
            fontFallback: [emoji],
            fontSize: 25,
          ),
        ),
      ); // Center
    })); // Page
```
