### ISSUE TITLE
[syncfusion_flutter_pdf] Japanese characters are not supported only in "headerRow of _getGrid()".

### ISSUE THREAD

**Issue by TakaTeke** [syncfusion/flutter-widgets#1530]
Hello.

I'm using "syncfusion_flutter_pdf". I want to output PDF with Japanese characters on MacOS. I am creating an application by referring to "invoice.dart", but only "headerRow of _getGrid()" does not support Japanese characters.

<< Code to specify font >>
headerRow.style.font = PdfCjkStandardFont(PdfCjkFontFamily.heiseiMinchoW3, 9, style: PdfFontStyle.bold);

The following message will be output and an error will occur. However, "rows in the grid", "_drawHeader" and "_drawFooter" support Japanese characters.
Please tell me what to do.
I have attached the application code at the end of the article.

<< Error message >>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'PdfCjkStandardFont' is not a subtype of type 'PdfTrueTypeFont' in type cast
#0      PdfGrid._createRegularFont (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid.dart:649:51)
#1      PdfGrid._changeFontStyle (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid.dart:687:17)
#2      PdfGrid._applyListTable4 (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid.dart:2782:31)
#3      PdfGridHelper.applyBuiltinStyles (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid.dart:4235:14)
#4      PdfGridLayouter._layoutOnPage (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/layouting/pdf_grid_layouter.dart:166:43)
#5      PdfGridLayouter.layoutInternal (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/layouting/pdf_grid_layouter.dart:1815:12)
#6      PdfGridHelper.layout (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid.dart:3852:34)
#7      PdfLayoutElementHelper.layout (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/figures/base/layout_element.dart:108:55)
#8      PdfLayoutElement._draw (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/figures/base/layout_element.dart:51:22)
#9      PdfLayoutElement.draw (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/figures/base/layout_element.dart:38:12)
#10     PdfGrid.draw (package:syncfusion_flutter_pdf/src/pdf/implementation/structured_elements/grid/pdf_grid.dart:546:17)
#11     _MyHomePageState._drawGrid (package:pdf_test/main.dart:161:19)
#12     _MyHomePageState._generatePDF (package:pdf_test/main.dart:108:5)
#13     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#15     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#16     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#17     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
#18     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#19     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#20     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#21     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#22     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#23     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#24     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#25     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#26     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
#27     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#28     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#29     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#30     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#31     _invoke1 (dart:ui/hooks.dart:186:13)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)

[main.dart.zip](https://github.com/syncfusion/flutter-widgets/files/13463060/main.dart.zip)

**Comment by TakaTeke** [comment]
I solved the problem myself.

After commenting out the line below, Japanese characters are now supported in "headerRow of _getGrid()".

"grid.applyBuiltInStyle(PdfGridBuiltInStyle.listTable4Accent5);"

I don't really know how to use "PdfGridBuiltInStyle", but once I deleted it, my purpose was achieved, so I'll close it as a self-solved problem.
