### ISSUE TITLE
[syncfusion_flutter_calendar]: some bugs.

### ISSUE THREAD

**Issue by kjxbyz** [syncfusion/flutter-widgets#1581]
1. setState() or markNeedsBuild() called during build.

```
[log] setState() or markNeedsBuild() called during build.
This _CalendarHeaderView widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  _CalendarHeaderView
The widget which was currently being built when the offending call was made was:
  _OpacityWidget
      #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5033:9)
      #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5045:6)
      #2      State.setState (package:flutter/src/widgets/framework.dart:1223:15)
      #3      _CalendarHeaderViewState._updateWeekNumberChangedForTimelineMonth (package:syncfusion_flutter_calendar/src/calendar/sfcalendar.dart:10280:5)
      #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
      #5      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
      #6      _CustomCalendarScrollViewState.didUpdateWidget (package:syncfusion_flutter_calendar/src/calendar/views/calendar_view.dart:469:50)
      #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5643:55)
      #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
      #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
      #12     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
      #13     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
      #14     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
      #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
      #17     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
      #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
      #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #20     Element.updateChildren (package:flutter/src/widgets/framework.dart:3964:32)
      #21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896:17)
      #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
      #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
      #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
      #28     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
      #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:5547:5)
      #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
      #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
      #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
      #36     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
      #37     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
      #38     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
      #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
      #41     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
      #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:5547:5)
      #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
      #44     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:132:18)
      #45     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835:19)
      #46     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:150:12)
      #47     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657:59)
      #48     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071:15)
      #49     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
      #50     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225:7)
      #51     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:308:5)
      #52     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #53     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #54     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279:14)
      #55     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #56     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #57     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:494:14)
      #58     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #59     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
      #61     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #62     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
      #64     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #65     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
      #67     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #68     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
      #70     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #71     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
      #73     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #74     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
      #76     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #77     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #78     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
      #79     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:581:43)
      #80     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:608:12)
      #81     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #82     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
      #84     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
      #85     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
      #86     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
      #87     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
      #88     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
      #89     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
      #90     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
      #91     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
      #92     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
      #93     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
      #94     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
      #95     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
      #96     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
      #97     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
      #98     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
      #99     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
      #100    _invoke (dart:ui/hooks.dart:312:13)
      #101    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
      #102    _drawFrame (dart:ui/hooks.dart:283:31)

```

```dart
SfCalendar(
          view: CalendarView.timelineMonth,
          dataSource: MeetingDataSource([]),
          onViewChanged: (ViewChangedDetails viewChangedDetails) {
            final visibleDates = viewChangedDetails.visibleDates;
            if (kDebugMode) {
              print('${viewChangedDetails.visibleDates}');
            }
            if(visibleDates.isNotEmpty) {
              final startDate = visibleDates.first;
            }
          },
          onSelectionChanged: (
            CalendarSelectionDetails calendarSelectionDetails,
          ) {
            if (kDebugMode) {
              print('${calendarSelectionDetails.resource}, ${calendarSelectionDetails.date}');
            }
          },
          onTap: (CalendarTapDetails calendarTapDetails) {
            final appointments = calendarTapDetails.appointments;
            if (appointments != null && appointments.isNotEmpty) {
              final appointment = calendarTapDetails.appointments!.first;
              if (appointment is RoadmapModel) {
                if (kDebugMode) {
                  print(appointment.title);
                }
              }
            }
          },
          showNavigationArrow: true,
          showDatePickerButton: true,
          showTodayButton: true,
          // allowViewNavigation: true,
          showWeekNumber: true,
          // allowAppointmentResize: true,
          headerDateFormat: 'MM/yyyy',
          monthViewSettings: const MonthViewSettings(
            appointmentDisplayCount: 5,
            appointmentDisplayMode: MonthAppointmentDisplayMode.appointment,
          ),
        )
```

2. The week number is not displayed in full

<img width="613" alt="20231216-133703@2x" src="https://github.com/syncfusion/flutter-widgets/assets/47768002/d6fad127-4ef1-4682-9060-36a533790ce1">

4. When `showNavigationArrow` is set to true, the week number sometimes does not change when the toggle button is clicked.

<img width="613" alt="20231216-133633@2x" src="https://github.com/syncfusion/flutter-widgets/assets/47768002/7cb75bfa-9e87-4ea0-aedf-2e2f894ad92f">

5. The two dates are displayed differently, the one above should prevail.

<img width="616" alt="20231216-133548@2x" src="https://github.com/syncfusion/flutter-widgets/assets/47768002/2404f3ea-5d1c-4663-9890-e4846b6b74d6">

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue regarding ﻿﻿the setState() or markNeedsBuild() called during the build has been fixed and rolled out in our Volume 1 2024 main release. To avoid this please upgrade your package to the latest version mentioned below.

Latest package: https://pub.dev/packages/syncfusion_flutter_calendar/versions/25.1.35
