### ISSUE TITLE
Trackball and Tooltip are not re-rendering after zoom or scroll

### ISSUE THREAD

**Issue by Nikzed** [syncfusion/flutter-widgets#1637]
Hi! I have an app where I have to choose 3 points on graph and compare it between each other, but I am facing a problem even at start of development, which is not allowing me to come any further.

So. The problem is that trackball (line) and tooltip is not attached to the point where it was set, it is attached for coordinates on screen where it was at that point.

https://github.com/syncfusion/flutter-widgets/assets/38156331/72b102f2-321c-4bd9-b4ff-0c9f98219a10

Expected behavior
The line is attached to the value it was chosen.

**Comment by Nikzed** [comment]
> Hi @Nikzed ,
>
> We have prepared a sample to display the trackball at the specific point while performing zooming, by using the [showByIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/showByIndex.html) method.

I'd love to thank you! I was able to achieve it with the next logic
```
int? trackballPosition = 0;

onTrackballPositionChanging: (args) {
  trackballPosition = args.chartPointInfo.chartDataPoint?.x?.toInt() - 1;
},
```

**Comment by Nikzed** [comment]
The problem is I'm having and issue with applying it to DateTimeAxis.
```
======== Exception caught by gesture ===============================================================
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      TrackballBehavior.showByIndex (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:2982:15)
#1      _LineChartSampleState.chart.<anonymous closure> (package:graphs/screens/my_file.dart:196:18)
#2      ZoomPanBehavior._bindZoomEvent (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:1612:36)
#3      ZoomPanBehavior._pan.<anonymous closure> (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:1157:13)
#4      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4343:14)
#5      ZoomPanBehavior._pan (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:1124:12)
#6      RenderBehaviorArea._performPanning (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:522:24)
#7      RenderBehaviorArea.handleScaleUpdate (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:488:5)
#8      RenderChartArea._handleScaleUpdate (package:syncfusion_flutter_charts/src/charts/base.dart:608:22)
#9      ScaleGestureRecognizer._advanceStateMachine.<anonymous closure> (package:flutter/src/gestures/scale.dart:701:20)
#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#11     ScaleGestureRecognizer._advanceStateMachine (package:flutter/src/gestures/scale.dart:700:9)
#12     ScaleGestureRecognizer.handleEvent (package:flutter/src/gestures/scale.dart:552:7)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439:11)
#21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#25     _invoke1 (dart:ui/hooks.dart:328:13)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
Handler: "onUpdate"
```

I am having it in this spot of showByIndex method
```
parent!.plotArea!.firstChild! as CartesianSeriesRenderer?;
```

I've also adapted it for a DateTime values
```
onTrackballPositionChanging: (args) {
        int? newValue = args.chartPointInfo.chartDataPoint?.xValue?.toInt();
        trackballPosition = newValue != null ? newValue - 1 : null;
      },
```

**Comment by Nikzed** [comment]
In my code there was a problem that `TrackballBehavior` and `CrosshairBehavior` were declared inside method the graph was created, so it led to this errors.

It is lagging in my code still, because it got to search through a big dataset of data, but on a small app it should work perfectly fine with the next code:

```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  runApp(
    const MaterialApp(
      home: BD544494(),
      debugShowCheckedModeBanner: false,
    ),
  );
}

class BD544494 extends StatefulWidget {
  const BD544494({Key? key}) : super(key: key);

  @override
  _BD544494State createState() => _BD544494State();
}

class _BD544494State extends State<BD544494> {
  late TrackballBehavior _trackballBehavior;
  List<ChartData> chartData = [
    ChartData(DateTime(2024, 1, 1), 35.0),
    ChartData(DateTime(2024, 1, 2), 23.0),
    ChartData(DateTime(2024, 1, 3), 34.0),
    ChartData(DateTime(2024, 1, 4), 25.0),
    ChartData(DateTime(2024, 1, 5), 40.0),
    ChartData(DateTime(2024, 1, 6), 44.0),
    ChartData(DateTime(2024, 1, 7), 32.0),
    ChartData(DateTime(2024, 1, 8), 47.0),
    ChartData(DateTime(2024, 1, 9), 54.0),
    ChartData(DateTime(2024, 1, 10), 55.0),
    ChartData(DateTime(2024, 1, 11), 47.0),
  ];

  @override
  void initState() {
    _trackballBehavior = TrackballBehavior(
      enable: true,
      activationMode: ActivationMode.longPress,
      shouldAlwaysShow: true,
    );
    super.initState();
  }

  void _showTrackball() {
    _trackballBehavior.showByIndex(3);
  }

  DateTime? trackballPosition;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: _showTrackball,
              child: const Text('Show Trackball'),
            ),
            const SizedBox(height: 16),
            SfCartesianChart(
              zoomPanBehavior: ZoomPanBehavior(
                enableDoubleTapZooming: true,
                enablePanning: true,
              ),
              onTrackballPositionChanging: (args) {
                trackballPosition = args.chartPointInfo.chartDataPoint?.x;
              },
              trackballBehavior: _trackballBehavior,
              onZooming: (zoomingArgs) {
                trackballPosition == null
                    ? null
                    : _trackballBehavior.showByIndex(
                        chartData.indexWhere(
                          (element) => element.x == trackballPosition,
                        ),
                      );
              },
              onZoomStart: (zoomingArgs) {
                trackballPosition == null
                    ? null
                    : _trackballBehavior.showByIndex(
                        chartData.indexWhere(
                          (element) => element.x == trackballPosition,
                        ),
                      );
              },
              onZoomEnd: (zoomingArgs) {
                trackballPosition == null
                    ? null
                    : _trackballBehavior.showByIndex(
                        chartData.indexWhere(
                          (element) => element.x == trackballPosition,
                        ),
                      );
              },
              primaryXAxis: const DateTimeAxis(),
              primaryYAxis: const NumericAxis(),
              tooltipBehavior: TooltipBehavior(enable: true),
              series: <CartesianSeries<ChartData, DateTime>>[
                FastLineSeries(
                  dataSource: chartData,
                  xValueMapper: (ChartData data, _) => data.x,
                  yValueMapper: (ChartData data, _) => data.y,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class ChartData {
  ChartData(this.x, this.y);

  final DateTime x;
  final double y;
}

```
