### ISSUE TITLE
Error: Invalid argument (position): Invalid position: -1

### ISSUE THREAD

**Issue by Ejazullah579** [syncfusion/flutter-widgets#1653]
Getting the following error while loading project asset.
I am trying to extract text from pdf but getting stuck at initial line.
This is the link i am following
[https://www.syncfusion.com/blogs/post/5-ways-to-extract-text-from-pdf-documents-in-flutter.aspx](url)

And here is the complete Error

Uncaught (in promise) Error: Invalid argument (position): Invalid position: -1
    at Object.throw_ [as throw] (dart_sdk.js:5402:11)
    at set position (stream_reader.dart:22:7)
    at set position (pdf_reader.dart:55:18)
    at [_initialize] (cross_table.dart:120:11)
    at new cross_table.CrossTable.new (cross_table.dart:27:5)
    at [_initializeCrossTable] (pdf_cross_table.dart:182:18)
    at new pdf_cross_table.PdfCrossTable.new (pdf_cross_table.dart:41:9)
    at [_initialize] (pdf_document.dart:783:28)
    at new pdf_document.PdfDocument.new (pdf_document.dart:78:5)
    at pdfToText (pdf_to_text.dart:16:26)
    at pdfToText.next (<anonymous>)
    at dart_sdk.js:39902:33
    at _RootZone.runUnary (dart_sdk.js:39737:59)
    at _FutureListener.thenAwait.handleValue (dart_sdk.js:35127:29)
    at handleValueCallback (dart_sdk.js:35709:49)
    at _Future._propagateToListeners (dart_sdk.js:35747:17)
    at [_completeWithValue] (dart_sdk.js:35588:23)
    at async._AsyncCallbackEntry.new.callback (dart_sdk.js:35622:35)
    at Object._microtaskLoop (dart_sdk.js:40214:13)
    at _startMicrotaskLoop (dart_sdk.js:40220:13)
    at dart_sdk.js:35968:9

**Comment by jeyalakshmit** [comment]
We are trying to replicate the problem on our end using our test documents and we are not able to reproduce it. So, we kindly request you to share the input PDF document with us so that we can replicate the problem on our end. It will be more helpful for us to analyze further and provide you with a prompt solution.
