### ISSUE TITLE
[syncfusion_flutter_charts] RenderDateTimeCategoryAxis is not a subtype of type DateTimeCategoryAxis in type cast

### ISSUE THREAD

**Issue by cirediew** [syncfusion/flutter-widgets#1682]
`syncfusion_flutter_charts: ^24.2.7`
```
flutter: main onError caught:
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following _TypeError was thrown while handling a gesture:
flutter: type 'RenderDateTimeCategoryAxis' is not a subtype of type 'DateTimeCategoryAxis' in type cast
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      TrackballBehavior._trackballLabelText (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:3792:46)
flutter: #1      TrackballBehavior._generateAllPoints.<anonymous closure> (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:3309:32)
flutter: #2      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4343:14)
flutter: #3      TrackballBehavior._generateAllPoints (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:3253:23)
flutter: #4      TrackballBehavior.show (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:2944:7)
flutter: #5      RenderBehaviorArea._showTrackball (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:639:24)
flutter: #6      RenderBehaviorArea.handleLongPressStart (package:syncfusion_flutter_charts/src/charts/interactions/behavior.dart:445:7)
flutter: #7      RenderChartArea._handleLongPressStart (package:syncfusion_flutter_charts/src/charts/base.dart:524:22)
flutter: #8      LongPressGestureRecognizer._checkLongPressStart.<anonymous closure> (package:flutter/src/gestures/long_press.dart:703:75)
flutter: #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
flutter: #10     LongPressGestureRecognizer._checkLongPressStart (package:flutter/src/gestures/long_press.dart:703:11)
flutter: #11     LongPressGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/long_press.dart:607:5)
flutter: #12     PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:658:5)
flutter: #13     PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:601:41)
flutter: #17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
flutter: (elided 3 frames from class _Timer and dart:async-patch)
flutter:
flutter: Handler: "onLongPressStart"
flutter: Recognizer:
flutter:   LongPressGestureRecognizer#71a5d
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: ☢️️️ [10:08:31.009] package:app/main.dart:94:9 :: ERROR: FlutterError
flutter: ☢️️️ [10:08:31.009] package:app/main.dart:94:9 :: EXCEPTION: type 'RenderDateTimeCategoryAxis' is not a subtype of type 'DateTimeCategoryAxis' in type cast
```

`xAxis` is cast to the wrong type in `src/charts/interactions/behavior.dart` `_trackballLabelText`

`behavior.dart:3787`: 
```dart
} else if (xAxis is RenderDateTimeCategoryAxis) {
        final num interval = xAxis.visibleRange!.minimum.ceil();
        final num prevInterval = (xAxis.visibleLabels.isNotEmpty)
            ? xAxis.visibleLabels[xAxis.visibleLabels.length - 1].value
            : interval;
        final DateFormat dateFormat = (xAxis as DateTimeCategoryAxis)
                .dateFormat ??
            _dateTimeLabelFormat(xAxis, interval.toInt(), prevInterval.toInt());
        x = dateFormat.format(DateTime.fromMillisecondsSinceEpoch(
            dataPoint.x.millisecondsSinceEpoch));
      }
```
Changing line 3792
```dart
final DateFormat dateFormat = (xAxis as DateTimeCategoryAxis)
```
to
```dart
final DateFormat dateFormat = (xAxis as RenderDateTimeCategoryAxis)
```
fixed the issue for me.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need any further assistance on this.
