### ISSUE TITLE
[syncfusion_flutter_charts] Trendlines with `isVisibleInLegend: false` throw `Exception`s

### ISSUE THREAD

**Issue by btrautmann** [syncfusion/flutter-widgets#1690]
Passing `isVisibleInLegend:false` to a `Trendline` object causes the following:

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'RenderErrorBox' is not a subtype of type 'RenderTrendlineStack?' in type cast
#0      ChartSeriesRenderer.trendlineContainer (package:syncfusion_flutter_charts/src/charts/series/chart_series.dart:770:42)
#1      ChartSeriesRenderer.markNeedsLayout (package:syncfusion_flutter_charts/src/charts/series/chart_series.dart:2286:5)
#2      RenderObject.reassemble (package:flutter/src/rendering/object.dart:1685:5)
#3      RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1690:13)
#4      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4372:14)
#5      RenderObject.reassemble (package:flutter/src/rendering/object.dart:1689:5)
#6      RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1690:13)
#7      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4372:14)
#8      RenderObject.reassemble (p<…>
```

You can reproduce this by running the following project: https://github.com/btrautmann/syncfusion_charts_repros

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need any further assistance on this.
