### ISSUE TITLE
Setting X axis to not be visible causes a crash when resizing the window (MacOS)

### ISSUE THREAD

**Issue by av4625** [syncfusion/flutter-widgets#1861]
### Bug description

When I add `primaryXAxis: NumericAxis(isVisible: false),` to a `SfCartesianChart` and then resize the flutter app window the application crashes. Remove this line and it works fine.

One interesting thing to note, if you re-add this line and do a hot reload, it does not crash until the chart has been fully redrawn again or a hot restart has happened. Even though the hot reload does show the change to the axis visually.

### Steps to reproduce

Add `primaryXAxis: NumericAxis(isVisible: false),` to a chart and try and resize the flutter app window on MacOS (Can't confirm if it happens on other devices)

### Code sample

<details open><summary>Code sample</summary>

The following shows the chart I am using, this chart is the child of an `Expanded` widget inside a `Column` of other `Expanded` widgets containing charts. (This same issue happens in the other charts, they are almost identical to this chart with related data)

``` dart
class _SpeedDistance {
  const _SpeedDistance(this.speed, this.distance);

  final double speed;
  final double distance;
}

class SpeedChart extends Chart {
  SpeedChart(
    final HoverHandler hoverHandler,
    {super.key, super.showXAxis}
  ) : _hoverHandler = hoverHandler {
    _trackballBehaviour = ExitableTrackballBehaviour(
      shouldAlwaysShow: true,
      activationMode: ActivationMode.singleTap,
      enable: true,
      tooltipDisplayMode: TrackballDisplayMode.none,
      markerSettings: const TrackballMarkerSettings(
        markerVisibility: TrackballVisibilityMode.visible),
      onPointerHover: (final Offset position, final double maxWidth) =>
        _hoverHandler.hover(chartType, position, maxWidth),
      onPointerExit: () => _hoverHandler.hoverExit(chartType)
    );

    _hoverHandler.addHoverHandler(
      chartType,
      (final Offset position, final double maxWidth) {
        _trackballBehaviour.show(
          position.dx.remapAndClamp(
            0,
            maxWidth,
            0,
            _trackballBehaviour.parentBox?.size.width ?? 0),
          position.dy,
          "pixel");
      }
    );
    _hoverHandler.addHideHandler(chartType, () => _trackballBehaviour.hide());
  }

  final HoverHandler _hoverHandler;
  late final ExitableTrackballBehaviour _trackballBehaviour;

  @override
  ChartType get chartType => ChartType.speed;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final RunData runData = ref.watch(runDataProvider);

    if (runData.isEmpty) {
      return const SizedBox.shrink();
    }

    return SfCartesianChart(
      trackballBehavior: _trackballBehaviour,
      primaryXAxis: const NumericAxis(isVisible: false),
      series: _buildLineData(runData),
    );
  }

  List<LineSeries<_SpeedDistance, double>> _buildLineData(
    final RunData runData
  ) {
    final List<LineSeries<_SpeedDistance, double>> lineData =
      <LineSeries<_SpeedDistance, double>>[];

    for (final (index, run) in runData.runNames.indexed) {
      if (runData.getIsActive(run) && runData.getAltitudes(run).isNotEmpty) {
        lineData.add(LineSeries<_SpeedDistance, double>(
          name: run,
          animationDuration: 0,
          enableTooltip: false,
          width: 1.5,
          color: (index < chartLineColours.length)
            ? chartLineColours[index] : null,
          dataSource: () {
            final List<double> speeds = runData.getSpeeds(run);
            final List<double> distances = runData.getDistances(run);

            return List<_SpeedDistance>.generate(
              distances.length,
              (index) {
                return _SpeedDistance(speeds[index], distances[index]);
              }
            );
          }(),
          xValueMapper: (final _SpeedDistance data, _) => data.distance,
          yValueMapper: (final _SpeedDistance data, _) => data.speed,
        ));
      }
    }

    return lineData;
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/syncfusion/flutter-widgets/assets/19472253/3de4dd0a-7135-4423-a53f-27de8df27d24

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart


════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
A LineSeriesRenderer<_SpeedDistance, double> was mutated in RenderNumericAxis.performLayout.
A RenderObject must not mutate another RenderObject from a different render subtree in its performLayout method.
The RenderObject being mutated was: LineSeriesRenderer<_SpeedDistance, double>#8d5c2
    parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=548.1, 0.0<=h<=272.7)
    size: Size(548.1, 272.7)
The RenderObject that was mutating the said LineSeriesRenderer<_SpeedDistance, double> was: RenderNumericAxis#dee9f relayoutBoundary=up10
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=575.5, 0.0<=h<=272.7)
    size: Size(31.9, 272.7)
Their common ancestor was: RenderCartesianChartArea#59e34 relayoutBoundary=up8
    needs compositing
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=575.5, 0.0<=h<=272.7)
    layer: OffsetLayer#9f7b1
    size: Size(580.0, 272.7)
Mutating the layout of another RenderObject may cause some RenderObjects in its subtree to be laid out more than once. Consider using the LayoutBuilder widget to dynamically mutate a subtree during layout.

The relevant error-causing widget was:
    SfCartesianChart SfCartesianChart:file:///Users/avance/Documents/Development/Flutter/race_data_analyser/lib/component/charts/speed.dart:68:12

When the exception was thrown, this was the stack:
#0      RenderObject._debugCanPerformMutations.<anonymous closure> (package:flutter/src/rendering/object.dart:2052:7)
#1      RenderObject._debugCanPerformMutations (package:flutter/src/rendering/object.dart:2075:6)
#2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2281:12)
#3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2379:11)
#4      ChartSeriesRenderer.markNeedsLayout (package:syncfusion_flutter_charts/src/charts/series/chart_series.dart:2285:11)
#5      CartesianSeriesRenderer.didRangeChange (package:syncfusion_flutter_charts/src/charts/series/chart_series.dart:3676:7)
#6      RenderChartAxis._calculateRangeAndInterval.<anonymous closure> (package:syncfusion_flutter_charts/src/charts/axis/axis.dart:1983:21)
#7      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2686:59)
#8      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097:15)
#9      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2686:14)
#10     RenderChartAxis._calculateRangeAndInterval (package:syncfusion_flutter_charts/src/charts/axis/axis.dart:1981:7)
#11     RenderChartAxis.performLayout (package:syncfusion_flutter_charts/src/charts/axis/axis.dart:1772:7)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#13     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#14     RenderCartesianAxes.performLayout.measureVerticalAxes (package:syncfusion_flutter_charts/src/charts/base.dart:2057:14)
#15     RenderCartesianAxes.performLayout (package:syncfusion_flutter_charts/src/charts/base.dart:2073:5)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#17     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#18     RenderCartesianChartArea.performLayout (package:syncfusion_flutter_charts/src/charts/base.dart:851:23)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#20     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#21     _RenderLegendLayoutHandler.performLayout (package:syncfusion_flutter_charts/src/charts/common/core_legend.dart:989:15)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#24     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#27     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#36     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#37     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:869:45)
#38     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:904:32)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#41     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#43     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#44     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#45     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:869:45)
#46     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:904:32)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#54     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#55     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:309:19)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#57     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139:12)
#58     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:160:11)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#60     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
#61     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1555:12)
#62     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1464:20)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#64     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#67     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#70     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#73     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#76     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#79     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#82     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#85     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#87     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#89     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#92     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#95     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#98     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#101    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#103    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#104    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#105    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#106    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1063:7)
#107    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#108    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#110    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#112    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#113    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#114    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#115    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1440:11)
#116    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#117    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#118    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#120    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#122    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#123    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#124    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#125    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#126    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#127    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#128    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#129    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#130    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#131    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:582:43)
#132    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:609:12)
#133    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#134    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#135    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#136    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#137    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#138    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#139    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#140    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#141    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#142    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#143    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#144    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#145    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#146    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#147    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#148    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#149    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#150    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#151    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3728:13)
#152    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#153    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#154    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#155    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#156    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#157    _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:968:13)
#158    _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1282:9)
#159    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#160    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#161    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#162    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#163    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#164    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#165    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#166    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#167    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#168    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#169    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#170    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#171    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#172    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#173    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#174    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#175    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#176    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#177    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#178    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#179    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#180    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#181    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#182    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#183    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#184    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#185    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#186    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#187    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#188    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#189    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#190    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#191    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#192    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#193    RenderObject.layout (package:flutter/src/rendering/object.dart:2575:7)
#194    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#195    RenderView.performLayout (package:flutter/src/rendering/view.dart:195:14)
#196    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2414:7)
#197    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
#198    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
#199    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:582:23)
#200    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991:13)
#201    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#202    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#203    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#204    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#205    _invoke (dart:ui/hooks.dart:312:13)
#206    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#207    _drawFrame (dart:ui/hooks.dart:283:31)

The following RenderObject was being processed when the exception was fired: RenderNumericAxis#dee9f relayoutBoundary=up10
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=575.5, 0.0<=h<=272.7)
    size: Size(31.9, 272.7)
RenderObject: RenderNumericAxis#dee9f relayoutBoundary=up10
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=575.5, 0.0<=h<=272.7)
    size: Size(31.9, 272.7)
════════════════════════════════════════════════════════════════════════════════
Restarted application in 1,691ms.


```

</details>

### On which target platforms have you observed this bug?

macOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 12.7.4 21H1123 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by LokeshPalani** [comment]
Hi @av4625,

 
We have replicated the issue you reported on our end. This issue is scheduled to be fixed in our upcoming weekly release on **May 28, 2024.** We will provide you with more information. Thank you for your understanding and patience in the meantime.


Regards,
Lokesh P.

**Comment by av4625** [comment]
Hi @LokeshPalani, Thats great, thanks!

**Comment by LokeshPalani** [comment]
Hi @av4625,

We would like to let you know that the reported issue is fixed and rolled out in our patch release. We kindly request you to upgrade the syncfusion_flutter_charts package to the latest version below.

Version Link:  https://pub.dev/packages/syncfusion_flutter_charts/versions/25.2.6

 

Root cause: Due to the x-axis being set to false, there is no change in the y-axis constraints while resizing the window. Here, missed avoiding the recalculation of the chart range when resizing the window.

If you have any further queries, please feel free to reach out to us.

Regards,
Lokesh P.

**Comment by av4625** [comment]
@LokeshPalani it works perfect now, thank you
