### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Pdf viewer assertion was thrown building PdfScrollable setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by zakblacki** [syncfusion/flutter-widgets#2089]
### Bug description

- When I load/open a PDF file and then I try to zoom in and out a bug appears 
Note that the files are retrieved from cloudflare R2 storage 
it appears to be similar to  [this](https://stackoverflow.com/questions/47592301/setstate-or-markneedsbuild-called-during-build)

and yes I did try adding 

```
WidgetsBinding.instance.addPostFrameCallback((_){
      setState(() {
      _file = file;

});

```
Or 
```
      SchedulerBinding.instance.addPostFrameCallback((_) {
      setState(() {
      _file = file;
    });

```

But resulted same issue 

### Steps to reproduce

1. copy AppDownloadFile class 
2. input your own pdf url 
3. launch any files (more than one page) 
4. try to zoom in and out 

### Code sample

<details open><summary>Code sample</summary>

```dart
  class AppDownloadFile extends StatefulWidget {
    final FileModel file;
    final Widget? child;
    final Widget? success;
    final Widget? fail;
    final Widget? downloading;

    const AppDownloadFile({
      Key? key,
      required this.file,
      this.child,
      this.success,
      this.downloading,
      this.fail,
    }) : super(key: key);

    @override
    State<AppDownloadFile> createState() => _AppDownloadFileState();
  }
class _AppDownloadFileState extends State<AppDownloadFile> {
  double _percent = 0.0;
  bool _error = false;
  File? _file;

  @override
  void initState() {
    super.initState();
    _loadFile();
  }

  @override
  void dispose() {
    super.dispose();
  }

  ///Load file exist
  void _loadFile() async {
    final file = await UtilFile.loadFile(widget.file);
    setState(() {
      _file = file;
    });
  }

  ///Download file
  void _downloadFile() async {
    final response = await Api.requestDownloadFile(
        file: widget.file,
        progress: (percent) {
          setState(() {
            _percent = percent;
          });
        });

    if (!response.success) {
      setState(() {
        _error = true;
      });
      if (kDebugMode) {
        print('error');
      }
      AppBloc.messageBloc.add(MessageEvent(message: 'file does not exist'));
    } else {
      if (kDebugMode) {
        print('success');
      }
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => PdfViewerScreen(filePath: widget.file.url),
        ),
      );
      //_file = response.origin['data'];
    }
  }

  ///Download file
  void _openFile() {
    if (_file != null) {
      OpenFilex.open(_file!.path);
    }
  }

  ///Widget build child
  Widget _buildChild() {
    return InkWell(
      onTap: _downloadFile,
      child: Icon(
        Icons.cloud_download,
        color: Theme.of(context).colorScheme.secondary,
      ),
    );
  }

  ///Widget build fail
  Widget _buildFail() {
    return Container();
  }

  ///Widget build success
  Widget _buildSuccess() {
    return InkWell(
      onTap: _openFile,
      child: Icon(
        Icons.file_download_done,
        color: Theme.of(context).colorScheme.secondary,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    if (_error) {
      return widget.fail ?? _buildFail();
    }
    if (_file != null) {
      return widget.success ?? _buildSuccess();
    }
    return Container(
      child: widget.child ?? _buildChild(),
    );
  }
}

class PdfViewerScreen extends StatelessWidget {
  final String filePath;

  const PdfViewerScreen({super.key, required this.filePath});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(Translate.of(context).translate('menu')),
        ),
        body: SfPdfViewer.network(filePath));
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Screenshot: 
![Screenshot_2024-09-21-16-23-42-857_com dz partenaire](https://github.com/user-attachments/assets/a7b23d6d-e9bd-4f70-a637-dec9e14518a5)

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
======== Exception caught by widgets library =======================================================
The following assertion was thrown building PdfScrollable-[LabeledGlobalKey<PdfScrollableState>#57eb0](dirty, state: PdfScrollableState#17476):
setState() or markNeedsBuild() called during build.

This SfPdfViewer widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: SfPdfViewer
  dependencies: [Directionality, InheritedCupertinoTheme, MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#e3218]]
  state: SfPdfViewerState#a820d
The widget which was currently being built when the offending call was made was: PdfScrollable-[LabeledGlobalKey<PdfScrollableState>#57eb0]
  dirty
  state: PdfScrollableState#17476
The relevant error-causing widget was: 
  SfPdfViewer SfPdfViewer:file:///Users/g-besoin/Desktop/listar/lib/widgets/app_download_file.dart:165:27
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5177:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5189:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1223:15)
#3      SfPdfViewerState._checkMount (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3963:7)
#4      SfPdfViewerState._pageChanged (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3981:7)
#5      SfPdfViewerState._updateCurrentPageNumber (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:4299:5)
#6      SfPdfViewerState._handlePdfOffsetChanged (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:5758:9)
#7      PdfScrollableState._handlePdfOffsetChanged (package:syncfusion_flutter_pdfviewer/src/control/pdf_scrollable.dart:407:12)
#8      PdfScrollableState.build (package:syncfusion_flutter_pdfviewer/src/control/pdf_scrollable.dart:199:7)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#15     Element.updateChildren (package:flutter/src/widgets/framework.dart:4090:32)
#16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060:17)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#18     _LayoutBuilderElement._rebuildWithConstraints.updateChildCallback (package:flutter/src/widgets/layout_builder.dart:207:18)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038:19)
#20     _LayoutBuilderElement._rebuildWithConstraints (package:flutter/src/widgets/layout_builder.dart:231:12)
#21     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2719:59)
#22     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1098:15)
#23     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2719:14)
#24     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:278:5)
#25     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:369:5)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#31     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#32     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1092:7)
#33     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#34     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#35     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:7)
#36     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:18)
#37     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:15)
#38     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602:23)
#39     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
#40     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#41     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#42     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#43     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#47     _invoke (dart:ui/hooks.dart:314:10)
#48     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#49     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 3 frames from dart:async)

```

</details>

### On which target platforms have you observed this bug?

Android

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale
    en-DZ)
    • Flutter version 3.24.3 on channel stable at
      /Users/g-besoin/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (10 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/g-besoin/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/g-besoin/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/g-besoin/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • M2101K6G (mobile)               • 192.168.1.6:5555      • android-arm64  •
      Android 13 (API 33)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 129.0.6668.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by immankumarsync** [comment]
Hi @zakblacki,

We are unable to replicate the reported issue. Please find the video recording attached of the issue replication.

[Screen Recording.zip](https://github.com/user-attachments/files/17115462/Screen.Recording.zip)

Please share the following information to check this issue further.
1. The device details in which the issue occurs
2. The PDF document in which the issue occurs.
3. Replication video.

Could you please check with the latest version?
[syncfusion_flutter_pdfviewe 27.1.50](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/27.1.50)

Regards,
Imman Kumar P
