### ISSUE TITLE
hovering the mouse over the SfMaps polyline hangs/crashes the map on flutter web

### ISSUE THREAD

**Issue by Okiring** [syncfusion/flutter-widgets#209]
Each time i hover the mouse over the polyline, i get this error. Running flutter stable 2.0.5.
When the polyline is removed, everything works fine

Error: Assertion failed: file:///flutter/packages/flutter/lib/src/rendering/mouse_tracking.dart:311:12
!_debugDuringDeviceUpdate
is not true
    at Object.throw_ [as throw] (http://localhost:49411/dart_sdk.js:5333:11)
    at Object.assertFailed (http://localhost:49411/dart_sdk.js:5269:15)
    at mouse_tracking.MouseTracker.new.[_deviceUpdatePhase] (http://localhost:49411/packages/flutter/src/rendering/layer.dart.lib.js:5050:61)
    at http://localhost:49411/packages/flutter/src/rendering/layer.dart.lib.js:5108:33
    at mouse_tracking.MouseTracker.new.[_monitorMouseConnection] (http://localhost:49411/packages/flutter/src/rendering/layer.dart.lib.js:5045:7)
    at mouse_tracking.MouseTracker.new.updateWithEvent (http://localhost:49411/packages/flutter/src/rendering/layer.dart.lib.js:5107:36)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:49411/packages/flutter/src/rendering/layer.dart.lib.js:6081:46)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:49411/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:49411/packages/flutter/src/gestures/binding.dart.lib.js:258:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:49411/packages/flutter/src/gestures/binding.dart.lib.js:247:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:49411/packages/flutter/src/gestures/binding.dart.lib.js:237:65)
    at Object.invoke1 (http://localhost:49411/dart_sdk.js:183785:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:49411/dart_sdk.js:164267:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:49411/dart_sdk.js:164901:49)
    at http://localhost:49411/dart_sdk.js:165346:26
    at http://localhost:49411/dart_sdk.js:165311:16
    at http://localhost:49411/dart_sdk.js:165005:11

![Screen Shot 2021-05-01 at 8 20 54 PM](https://user-images.githubusercontent.com/27002476/116790017-cc1ca380-aaba-11eb-8f5e-13990b32f010.png)

**Comment by PraveenGopalsamy** [comment]
Hi @Okiring ,

We have fixed the issue and included it in our weekly release which is expected to be live by May 4, 2021.

Regards,
Praveen G.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi,   
  
As we mentioned earlier, we have included fix for the reported issue in our latest weekly release (19.1.59-beta). Kindly check and confirm whether the issue is resolved on your side.  
  
**Link:** https://pub.dev/packages/syncfusion_flutter_maps/install   
  
Regards,   
Lakshmi R.

**Comment by Okiring** [comment]
Thanks for the update. From testing and the issue is now resolved.
