### ISSUE TITLE
SplineAreaSeries在有些情况下无法绘制

### ISSUE THREAD

**Issue by changleibox** [syncfusion/flutter-widgets#239]
你好，我在使用贵公司的SplineAreaSeries控件的时候，在某些情况下无法绘制

插件版本
```yml
syncfusion_flutter_charts: ^19.1.64
```

下面是保存信息：

<details>
  <summary>Logs</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
flutter: The following _CastError was thrown:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _SplineAreaChartPainter.paint (package:syncfusion_flutter_charts/src/chart/series_painter/spline_area_painter.dart:135:46)
flutter: #1      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:564:13)
flutter: #2      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
flutter: #3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #5      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #7      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
flutter: #8      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
flutter: #9      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
flutter: #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
flutter: #11     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
flutter: #12     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
flutter: #13     RenderStack.paint (package:flutter/src/rendering/stack.dart:639:7)
flutter: #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #17     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2165:11)
flutter: #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #21     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2165:11)
flutter: #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #40     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2165:11)
flutter: #41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #43     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:384:15)
flutter: #44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #49     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:384:15)
flutter: #50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #52     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
flutter: #53     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1079:7)
flutter: #54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #56     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
flutter: #57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #59     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
flutter: #60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #62     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #63     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2165:11)
flutter: #64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #66     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
flutter: #67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #69     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #71     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
flutter: #72     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
flutter: #73     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
flutter: #74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
flutter: #75     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #78     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #79     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
flutter: #80     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:5044:13)
flutter: #81     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #82     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #83     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #85     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #86     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #87     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3375:11)
flutter: #88     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #90     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
flutter: #91     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
flutter: #92     RenderStack.paint (package:flutter/src/rendering/stack.dart:639:7)
flutter: #93     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #94     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #95     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #96     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #97     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #98     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #99     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3375:11)
flutter: #100    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #101    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #102    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #103    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #104    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #105    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
flutter: #106    RenderFlex.paint (package:flutter/src/rendering/flex.dart:1079:7)
flutter: #107    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #108    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #109    RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
flutter: #110    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #111    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #112    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
flutter: #113    RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2165:11)
flutter: #114    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #115    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #116    RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
flutter: #117    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #118    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #119    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
flutter: #120    RenderFlex.paint (package:flutter/src/rendering/flex.dart:1079:7)
flutter: #121    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #122    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #123    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
flutter: #124    RenderFlex.paint (package:flutter/src/rendering/flex.dart:1079:7)
flutter: #125    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #126    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #127    RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
flutter: #128    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #129    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #130    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
flutter: #131    RenderFlex.paint (package:flutter/src/rendering/flex.dart:1079:7)
flutter: #132    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #133    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #134    _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7694:15)
flutter: #135    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #136    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #137    RenderSliverSingleBoxAdapter.paint (package:flutter/src/rendering/sliver.dart:1781:15)
flutter: #138    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #139    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #140    RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:650:17)
flutter: #141    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
flutter: #142    PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:452:7)
flutter: #143    RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:637:32)
flutter: #144    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
flutter: #145    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
flutter: #146    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
flutter: #147    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
flutter: #148    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
flutter: #149    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
flutter: #150    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
flutter: #151    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #152    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #153    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter: #157    _invoke (dart:ui/hooks.dart:161:10)
flutter: #158    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
flutter: #159    _drawFrame (dart:ui/hooks.dart:120:31)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
```
</details>

**Comment by SriramKiranSenthilkumar** [comment]
Hi @changleibox,

Greetings from Syncfusion. We have analyzed your query at our end, and we tried to replicate the reported issue regarding the spline area series throwing exception. Unfortunately, we are not able to replicate the reported issue. So, we kindly request you to share us more information on the scenario in which the reported issue is replicating along with replication procedure rand also, if possible, share us the code snippet with your data source which you have used to render chart widget. 

Regards,
Sriram Kiran
