### ISSUE TITLE
my app stops after I open pdf file with syncfusion_flutter_pdfviewer: ^19.1.64-beta

### ISSUE THREAD

**Issue by hussam132** [syncfusion/flutter-widgets#251]
I'm using `syncfusion_flutter_pdfviewer: ^19.1.64-beta` to open pdf files the app works fine but when I Tried to open a new pdf file with a lots of images inside it  my app stop and it gives me this error
when I use other app to open my apps they works fine 
I'm using windows 10 with physical android device
please any help 
I will be glad to add any more details if any needs
```
 I/ViewRootImpl@3dcbcbe[MainActivity](18165): ViewPostIme pointer 0
I/ViewRootImpl@3dcbcbe[MainActivity](18165): ViewPostIme pointer 1
E/BufferQueueProducer(18165): [ImageReader-1080x2274f1m3-18165-0](id:46f500000000,api:0,p:-1,c:18165) disconnect: not connected (req=1)
W/libEGL  (18165): EGLNativeWindowType 0x7191c6b010 disconnect failed
I/example.img2pd(18165): Waiting for a blocking GC Alloc
I/example.img2pd(18165): Background young concurrent copying GC freed 4256(342KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 138MB/138MB, paused 3.116ms total 267.822ms
I/example.img2pd(18165): WaitForGcToComplete blocked Alloc on HeapTrim for 17.829ms
I/example.img2pd(18165): Starting a blocking GC Alloc
I/example.img2pd(18165): Forcing collection of SoftReferences for 134MB allocation
I/example.img2pd(18165): Starting a blocking GC Alloc
I/example.img2pd(18165): Alloc concurrent copying GC freed 5692(208KB) AllocSpace objects, 0(0B) LOS objects, 14% free, 138MB/162MB, paused 1.143ms total 47.454ms
I/example.img2pd(18165): WaitForGcToComplete blocked Background on HeapTrim for 44.917ms
W/example.img2pd(18165): Throwing OutOfMemoryError "Failed to allocate a 140567993 byte allocation with 25165824 free bytes and 53MB until OOM, target footprint 170193312, growth limit 201326592" (VmSize 8908288 kB)
2
I/example.img2pd(18165): Starting a blocking GC Alloc
I/example.img2pd(18165): Alloc young concurrent copying GC freed 4(31KB) AllocSpace objects, 0(0B) LOS objects, 14% free, 138MB/162MB, paused 252us total 15.401ms
I/example.img2pd(18165): Forcing collection of SoftReferences for 134MB allocation
I/example.img2pd(18165): Starting a blocking GC Alloc
I/example.img2pd(18165): Alloc concurrent copying GC freed 85(18KB) AllocSpace objects, 0(0B) LOS objects, 14% free, 138MB/162MB, paused 258us total 33.413ms
W/example.img2pd(18165): Throwing OutOfMemoryError "Failed to allocate a 140568000 byte allocation with 25165824 free bytes and 53MB until OOM, target footprint 170174344, growth limit 201326592" (VmSize 8908288 kB)
E/AndroidRuntime(18165): FATAL EXCEPTION: main
E/AndroidRuntime(18165): Process: com.example.myapp, PID: 18165
E/AndroidRuntime(18165): java.lang.OutOfMemoryError: Failed to allocate a 140568000 byte allocation with 25165824 free bytes and 53MB until OOM, target footprint 170174344, growth limit 201326592
E/AndroidRuntime(18165): 	at io.flutter.plugin.common.StandardMessageCodec.readBytes(StandardMessageCodec.java:298)
E/AndroidRuntime(18165): 	at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:362)
E/AndroidRuntime(18165): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
E/AndroidRuntime(18165): 	at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:48)
E/AndroidRuntime(18165): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/AndroidRuntime(18165): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(18165): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(18165): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(18165): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(18165): 	at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime(18165): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime(18165): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18165): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(18165): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
I/Process (18165): Sending signal. PID: 18165 SIG: 9
Lost connection to device.
```

**Comment by dillibabun** [comment]
Hi @hussam132 ,

We tried to reproduce the issue by loading the document with high-quality images(122 pages), the application was working as expected. We suspect the issue might be device or document-specific, so kindly share us the following details.
1. Device specification.
2. Issue reproducing PDF document with dummy information.

These details will help us to provide you a prompt solution at the earliest.

Regards,
Dilli babu.
