### ISSUE TITLE
[SfDataGrid] Navigating from onCellTap throws _debugDisposed and _debugDuringDeviceUpdate errors

### ISSUE THREAD

**Issue by ojm-it** [syncfusion/flutter-widgets#311]
Hello,

I'm using Flutter web (2.3.0-24.1.pre - channel beta). I have an SfDataGrid that I use like a file explorer. Each row represents a Folder, and when tapping on the row, it should navigate to the SubFolder's page. 

The problem I have is that if I use any Navigator function inside the "onCellTap" parameter, this error is thrown:

```
══════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed:
..\…\rendering\object.dart:2208
!_debugDisposed
is not true

When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/rendering/object.dart 2208:13                                                                         markNeedsPaint
packages/syncfusion_flutter_datagrid/src/control/cell_control/virtualizing_cells_widget.dart 826:7                         get onExit
packages/flutter/src/rendering/mouse_tracker.dart 394:58                                                                   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/rendering/mouse_tracker.dart 392:20                                                                   _handleDeviceUpdateMouseEvents
packages/flutter/src/rendering/mouse_tracker.dart 278:5                                                                    [_handleDeviceUpdate]
packages/flutter/src/rendering/mouse_tracker.dart 356:9                                                                    <fn>
packages/flutter/src/rendering/mouse_tracker.dart 206:9                                                                    [_deviceUpdatePhase]
packages/flutter/src/rendering/mouse_tracker.dart 350:5                                                                    updateAllDevices
packages/flutter/src/rendering/binding.dart 345:7                                                                          <fn>
packages/flutter/src/scheduler/binding.dart 1143:15                                                                        [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1088:9                                                                         handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                                                                          [_handleDrawFrame]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 964:13            invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 151:5             invokeOnDrawFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine.dart 395:45                                <fn>


Error: Assertion failed:
..\…\rendering\mouse_tracker.dart:201
!_debugDuringDeviceUpdate
is not true
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5368:11)
    at Object.assertFailed (http://localhost:5000/dart_sdk.js:5290:15)
    at mouse_tracker.MouseTracker.new.[_deviceUpdatePhase] (http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:5033:61)
    at http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:5099:33
    at mouse_tracker.MouseTracker.new.[_monitorMouseConnection] (http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:5028:7)
    at mouse_tracker.MouseTracker.new.updateWithEvent (http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:5098:36)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:5432:46)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:343:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:316:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:305:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:295:65)
    at Object.invoke1 (http://localhost:5000/dart_sdk.js:188070:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:5000/dart_sdk.js:171812:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:5000/dart_sdk.js:143781:49)
    at http://localhost:5000/dart_sdk.js:144227:26
    at http://localhost:5000/dart_sdk.js:144192:16
    at http://localhost:5000/dart_sdk.js:143885:11
```
The navigator does navigate to the desired page, but the entire UI freezes, and the debug console keeps logging the error when I hover the mouse on any UI element.

Here is for example one code sample that causes this error:

```
 SfDataGrid(
   ..........
   onCellTap : (details) {
       Navigator.of(context).pop(); 
   }
)
```

The same error is thrown when using push(), replace(), pushNamed... or any similar methods. It also occurs when using other SfDataGrid gesture methods such as onCellDoubleTap, onCellLongPress ...

I did some research and I found [this useful answer on StackOverflow](https://stackoverflow.com/a/55622474/13297133). However, the provided solutions did not work.

Flutter doctor :
```
[√] Flutter (Channel beta, 2.3.0-24.1.pre, on Microsoft Windows [version 10.0.19042.985], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[√] Chrome - develop for the web  
[√] Android Studio (version 4.0)  
[√] VS Code (version 1.57.1)      
[√] Connected device (2 available)

• No issues found!
```
Can you please help me?

**Comment by RenugaSadagoban98** [comment]
Hi @ojm-it ,  

Greetings from Syncfusion. 


From the provided information, we have checked cell tab callbacks (onCellTap, onCellDoubleTap, onCellLongPress, onCellSecondaryTap) with your reported scenario (Navigator. push, pop). but we could not reproduce your reported issue. 
 
Please find the following details, 
 
Platform: Web, 
Flutter Version: Flutter 2.3.0-24.1.pre • channel beta
DataGrid version: ^19.2.46 

Please refer to the following sample for your reference,  
https://www.syncfusion.com/downloads/support/directtrac/general/ze/lib-979708858 
 
Please check the above sample and revert us if you still facing the same issue?  It will be helpful for us to check on it and provide you the solution at the earliest.     

Regards,
Renuga devi S
