### ISSUE TITLE
[syncfusion_flutter_pdfviewer] _pdfViewerController.searchText() gives error if used in onDocumentLoaded() callback

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#314]
### Minimal reproducible example

<details>
<summary>code</summary>
<p>

```
import 'package:flutter/material.dart';

import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PDF viewer demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              child: Text(
                'Open PDF'
              ),
              onPressed: (){
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => MyPDFViewer()),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

class MyPDFViewer extends StatefulWidget {
  @override
  _MyPDFViewerState createState() => _MyPDFViewerState();
}

class _MyPDFViewerState extends State<MyPDFViewer> {
  final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey<SfPdfViewerState>();
  final PdfViewerController _pdfViewerController = PdfViewerController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("PDF Viewer"),
      ),
      body: Stack(
        children: <Widget>[
          Positioned.fill(
            child: SfPdfViewer.network(
              'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
              key: _pdfViewerKey,
              controller: _pdfViewerController,
              onDocumentLoaded: (PdfDocumentLoadedDetails details) {
                print("trying to find word");
                _pdfViewerController.searchText("Flutter");
              },
            ),
          ),
          Positioned(
            right: 50,
            bottom: 50,
            child: ElevatedButton(
              child: Text("Back"),
              onPressed: () {
                Navigator.pop(context);
              },
            ),
          ),
        ],
      )
    );
  }
}
```
</p>
</details>

### Issue

- If `_pdfViewerController.searchText("Flutter")` is used immediately after document load in `onDocumentLoaded()` callback then it gives below errors.
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      SfPdfViewerState._jumpToSearchInstance (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:1756:26)
#1      SfPdfViewerState._handleControllerValueChange (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:1697:11)
#2      _ValueChangeNotifier.notifyPropertyChangedListeners (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:2793:15)
#3      PdfViewerController.searchText (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:2679:5)
#4      _MyPDFViewerState.build.<anonymous closure> (package:flutter_app/main.dart:85:38)
#5      SfPdfViewerState._loadPdfDocument (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:863:33)
<asynchronous suspension>
```

- Error will happen only when `totalInstanceCount` is more then 0. If `totalInstanceCount` is 0 then there will be no error.

- This can be reproduced in any PDF from asset, file, memory or network.

### Expected behaviour

- `_pdfViewerController.searchText("Flutter")` should not produce any error even if it is used immediately after document load in `onDocumentLoaded()` callback.

**Comment by deepika134** [comment]
Hi sagarkardani,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 19 July 2021.

Regards,
Deepika R

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

We confirmed that the issue with " _pdfViewerController.searchText() gives error if used in onDocumentLoaded () callback" is a defect. The issue fix will be included in our Aug 1st weekly package release which is estimated to be available on 5 August 2021 tentatively.

The status of this issue can be tracked from [here](https://www.syncfusion.com/feedback/27157/exception-is-thrown-while-performing-text-search-in-ondocumentloaded-callback)

Regards,
Dilli babu

**Comment by deepika134** [comment]
Hi sagarkardani, 

we have included the fix for this issue " _pdfViewerController.searchText() gives an error if used in onDocumentLoaded () callback " in our latest weekly NuGet release, so kindly upgrade to the latest version v19.2.51 to get the issue resolved. 
 
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer
 
Regards,
Deepika R
