### ISSUE TITLE
[syncfusion_flutter_datagrid] Rebuilding SfDataGrid when previous grid was scrolled horizontally is causing the error

### ISSUE THREAD

**Issue by qbait** [syncfusion/flutter-widgets#357]
Sample app to reproduce the error:
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Syncfusion DataGrid Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool isAnotherGrid = false;
  late BullGrid grid1;
  late BullGrid grid2;

  @override
  void initState() {
    super.initState();

    final columns1 = List<String>.generate(20, (index) => 'column$index');
    final cells1 = columns1.map((e) => DataGridCell(columnName: e, value: e)).toList();
    final rows1 = List<DataGridRow>.generate(200, (index) => DataGridRow(cells: cells1));
    grid1 = BullGrid(rows1, columns1);

    final columns2 = List<String>.generate(20, (index) => 'column$index');
    final cells2 = columns2.map((e) => DataGridCell(columnName: e, value: e)).toList();
    final rows2 = List<DataGridRow>.generate(2, (index) => DataGridRow(cells: cells2));
    grid2 = BullGrid(rows2, columns2);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      floatingActionButton: FloatingActionButton.extended(
        label: Text('Switch grid'),
        onPressed: () => setState(() => isAnotherGrid = !isAnotherGrid),
      ),
      body: isAnotherGrid ? grid2 : grid1,
    );
  }
}

class BullGrid extends StatelessWidget {
  final Iterable<DataGridRow> rows;
  final Iterable<String> columns;

  BullGrid(
    this.rows,
    this.columns,
  );

  @override
  Widget build(BuildContext context) {
    return SfDataGrid(
      source: BullGridSource(rows),
      columns: columns.map((e) => _column(e)).toList(),
    );
  }

  GridTextColumn _column(String column) {
    return GridTextColumn(
      width: 100,
      columnName: column,
      label: Text(column),
    );
  }
}

class BullGridSource extends DataGridSource {
  final Iterable<DataGridRow> dataRows;

  BullGridSource(this.dataRows);

  @override
  List<DataGridRow> get rows => dataRows.toList();

  @override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map(
      (cell) {
        return Text(cell.value);
      },
    ).toList());
  }
}
```

How to reproduce:
1. Click `Switch grid`
2. Swipe grid horizontally to the end
3. Click `Switch grid`
4. The app is crashing with the following stack trace

```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building _VirtualizingCellsWidget-[DataRow#9e9ec](dirty, state: _VirtualizingCellsWidgetState#c9c44):
Null check operator used on a null value

The relevant error-causing widget was: 
  SfDataGrid file:///Users/jakub/StudioProjects/flutter-widgets/packages/syncfusion_flutter_datagrid/example/lib/main.dart:77:12
When the exception was thrown, this was the stack: 
#0      _VirtualizingCellsWidgetState.build.<anonymous closure> (package:syncfusion_flutter_datagrid/src/control/cell_control/virtualizing_cells_widget.dart:26:74)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#3      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:93:27)
#4      new _List.of (dart:core-patch/array.dart:55:20)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderErrorBox#f87f0 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2653 pos 12: '!_needsLayout'
```

**Comment by RenugaSadagoban98** [comment]
Hi @qbait , 
 
Sorry for the inconvenience.   
  
Due to some technical difficulties and more use cases needs to be ensured, we were unable to include the fix for the reported issue on September 7th weekly pub release.  We will include the changes in our next weekly pub release which is scheduled to be rolled out on 14th September 2021.  

We appreciate your patience until then.  

Regards,
Renugadevi

**Comment by RenugaSadagoban98** [comment]
Hi @qbait ,  
Thank you for your patience.
 
The reported issue “The null reference exception has been thrown while switching the DataGridSource after scrolling is performed” has been resolved and we have included the changes in our weekly pub release. Please update datagrid package to the 19.2.62-beta version. 

link: https://pub.dev/packages/syncfusion_flutter_datagrid/versions/19.2.62-beta

Regards,  
Renugadevi
