### ISSUE TITLE
[SfCalendar] _handleScheduleViewScrolled throws Error when filtering DataSource of Calendar

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#444]
I am trying to add filter functionality for the appointments. 

To achieve this, I currently filter the CalendarDataSource like so: 

```
class AssessmentViewModelDataSource extends CalendarDataSource {
  AssessmentViewModelDataSource(
      List<ViewModel> source, FilterOptions filterOptions) {
    final filteredSource = source
        .where((element) => element.name
            .toLowerCase()
            .contains(filterOptions.searchString.toLowerCase()))
        .toList();

    appointments = filteredSource;
  }

 ... other overrides follow here
 }
```

The filtering works as intended but when I scroll the scheduleview to the top, I get the following Error: 

```
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following RangeError was thrown while dispatching notifications for ScrollController:
flutter: RangeError (index): Invalid value: Not in inclusive range 0..3: 4
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.[] (dart:core-patch/growable_array.dart:254:60)
flutter: #1      _SfCalendarState._handleScheduleViewScrolled package:syncfusion_flutter_calendar/…/calendar/sfcalendar.dart:2590

flutter: #2      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:308

flutter: #3      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:308

flutter: #4      ScrollPosition.notifyListeners
package:flutter/…/widgets/scroll_position.dart:968

flutter: #5      ScrollPosition.setPixels
package:flutter/…/widgets/scroll_position.dart:278

flutter: #6      ScrollPositionWithSingleContext.setPixels
package:flutter/…/widgets/scroll_position_with_single_context.dart:82

flutter: #7      BallisticScrollActivity.applyMoveTo
package:flutter/…/widgets/scroll_activity.dart:566

flutter: #8      BallisticScrollActivity._tick
package:flutter/…/widgets/scroll_activity.dart:553

flutter: #9      AnimationLocalListenersMixin.notifyListeners
package:flutter/…/animation/listener_helpers.dart:155

flutter: #10     AnimationController._tick
package:flutter/…/animation/animation_controller.dart:829

flutter: #11     Ticker._tick
package:flutter/…/scheduler/ticker.dart:238

flutter: #12     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143

flutter: #13     SchedulerBinding.handleBeginFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:1056

flutter: #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)

flutter: #15     SchedulerBinding.handleBeginFrame
package:flutter/…/scheduler/binding.dart:1054

flutter: #16     SchedulerBinding._handleBeginFrame
package:flutter/…/scheduler/binding.dart:975

flutter: #20     _invoke1 (dart:ui/hooks.dart:185:10)

flutter: #21     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)

flutter: #22     _beginFrame (dart:ui/hooks.dart:116:31)

flutter: (elided 3 frames from dart:async)
flutter:
flutter: The ScrollController sending notification was:
flutter:   ScrollController#73c8f(initialScrollOffset: 1380.0, , one client, offset -748.1)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

How do I fix it?

**Comment by Wizzel1** [comment]
Nevermind, I forgot to wrap the filter button in 

`    SchedulerBinding.instance!.addPostFrameCallback((timeStamp) { });
`

**Comment by Wizzel1** [comment]
`SchedulerBinding.instance!.addPostFrameCallback((timeStamp) { });` doesnt always work...

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: I scroll the scheduleview to the top, I get the following Error.**

Based on the shared information, we have checked the mentioned issue “**Error occurred when scrolling to the top with appointments in Schedule view of the Flutter Calendar**”. We are unable to reproduce any error from our end. We have checked the mentioned error in custom appointment with schedule view and it was working fine as expected. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/scheduleview_app1017632528.zip

If possible, please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with the following details.

•	Replication procedure
•	Code snippet

It will be helpful for us to check on it and provide you solution at the earliest. 

Regards,
Indumathi R
