### ISSUE TITLE
"Null check operator used on a null value" when painting SfCartesianChart with SplineAreaSeries 

### ISSUE THREAD

**Issue by Goncharo** [syncfusion/flutter-widgets#447]
Lib Version: `syncfusion_flutter_charts: ^19.2.62`
Flutter Version: `2.5.2`

Sporadically, I'm getting a "Null check operator used on a null value" exception being thrown when rendering when an SfCartesianChart with a SplineAreaSeries. This usually happens when navigating to 2 pages up the stack, and then popping back down to the main page where the chart was initially rendered, but I'm not sure if this is relevant.

Seems very similar to issue https://github.com/syncfusion/flutter-widgets/issues/172 , which was closed due to no reproduction.

Example code:
```
SfCartesianChart(
            margin: EdgeInsets.zero,
            plotAreaBorderColor: Colors.transparent,
            plotAreaBorderWidth: 0.0,
            axisLabelFormatter: (args) {
              ChartAxisLabel label = ChartAxisLabel(args.text, args.textStyle);
              if (args.axisName == 'primaryXAxis' && args.text == todayStr) {
                TextStyle textStyle = args.textStyle
                    .copyWith(color: Theme.of(context).colorScheme.primary);
                label = ChartAxisLabel(args.text, textStyle);
              }
              return label;
            },
            primaryXAxis: DateTimeAxis(
              isVisible: true,
              interval: 1,
              intervalType: DateTimeIntervalType.days,
              dateFormat: DateFormat.E(),
              minimum: weekAgo,
              maximum: max,
              edgeLabelPlacement: EdgeLabelPlacement.shift,
            ),
            primaryYAxis: NumericAxis(
                    isVisible: true,
                    numberFormat: NumberFormat.compact(),
                    visibleMinimum: 0,
                  ),
            series: _buildLineSeries(range),
          );
          
 List<ChartSeries<MetricValue, DateTime>> _buildLineSeries(
    DateTimeRange range) {
  List<ChartSeries<MetricValue, DateTime>> series = [];
  // some data here
  var valuesByDay = [];

  MarkerSettings? markerSettings;
  if (valuesByDay.length == 1) {
    markerSettings = MarkerSettings(
        isVisible: true,
        color: Colors.transparent,
        borderColor: Colors.purple..withOpacity(0.1),
        borderWidth: 1,
        height: 10,
        width: 10);
  }
  series.add(SplineAreaSeries<MetricValue, DateTime>(
    animationDuration: 1000,
    splineType: SplineType.monotonic,
    enableTooltip: true,
    dataSource: valuesByDay,
    xValueMapper: (MetricValue val, _) => val.time,
    yValueMapper: (MetricValue val, _) => val.value,
    color:Colors.purple.withOpacity(0.2),
    borderColor: Colors.purple,
    dataLabelSettings: const DataLabelSettings(
      isVisible: false,
    ),
    borderWidth: 1,
    markerSettings: markerSettings,
  ));
  return series;
}       
```

Full stack trace:

```
Restarted application in 990ms.

════════ Exception caught by rendering library ═════════════════════════════════
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was
SfCartesianChart
When the exception was thrown, this was the stack
#0      SplineAreaChartPainter.paint
#1      RenderCustomPaint._paintWithPainter
#2      RenderCustomPaint.paint
#3      RenderObject._paintWithContext
#4      PaintingContext.paintChild
#5      RenderProxyBoxMixin.paint
#6      RenderObject._paintWithContext
#7      PaintingContext._repaintCompositedChild
#8      PaintingContext.repaintCompositedChild
#9      PaintingContext._compositeChild
#10     PaintingContext.paintChild
#11     RenderBoxContainerDefaultsMixin.defaultPaint
#12     RenderStack.paintStack
#13     RenderStack.paint
#14     RenderObject._paintWithContext
#15     PaintingContext.paintChild
#16     RenderProxyBoxMixin.paint
#17     RenderDecoratedBox.paint
#18     RenderObject._paintWithContext
#19     PaintingContext.paintChild
#20     RenderProxyBoxMixin.paint
#21     RenderDecoratedBox.paint
#22     RenderObject._paintWithContext
#23     PaintingContext.paintChild
#24     RenderProxyBoxMixin.paint
#25     RenderObject._paintWithContext
#26     PaintingContext.paintChild
#27     RenderProxyBoxMixin.paint
#28     RenderObject._paintWithContext
#29     PaintingContext.paintChild
#30     RenderProxyBoxMixin.paint
#31     RenderObject._paintWithContext
#32     PaintingContext.paintChild
#33     RenderProxyBoxMixin.paint
#34     RenderObject._paintWithContext
#35     PaintingContext.paintChild
#36     RenderProxyBoxMixin.paint
#37     RenderObject._paintWithContext
#38     PaintingContext.paintChild
#39     RenderProxyBoxMixin.paint
#40     RenderDecoratedBox.paint
#41     RenderObject._paintWithContext
#42     PaintingContext.paintChild
#43     _RenderLayoutBuilder.paint
#44     RenderObject._paintWithContext
#45     PaintingContext.paintChild
#46     RenderProxyBoxMixin.paint
#47     RenderObject._paintWithContext
#48     PaintingContext.paintChild
#49     _RenderLayoutBuilder.paint
#50     RenderObject._paintWithContext
#51     PaintingContext.paintChild
#52     RenderBoxContainerDefaultsMixin.defaultPaint
#53     RenderFlex.paint
#54     RenderObject._paintWithContext
#55     PaintingContext.paintChild
#56     RenderShiftedBox.paint
#57     RenderObject._paintWithContext
#58     PaintingContext.paintChild
#59     RenderShiftedBox.paint
#60     RenderObject._paintWithContext
#61     PaintingContext.paintChild
#62     RenderProxyBoxMixin.paint
#63     RenderDecoratedBox.paint
#64     RenderObject._paintWithContext
#65     PaintingContext.paintChild
#66     RenderShiftedBox.paint
#67     _ChartContainerBox.paint
#68     RenderObject._paintWithContext
#69     PaintingContext.paintChild
#70     RenderProxyBoxMixin.paint
#71     RenderObject._paintWithContext
#72     PaintingContext._repaintCompositedChild
#73     PaintingContext.repaintCompositedChild
#74     PaintingContext._compositeChild
#75     PaintingContext.paintChild
#76     RenderProxyBoxMixin.paint
#77     RenderObject._paintWithContext
#78     PaintingContext.paintChild
#79     RenderBoxContainerDefaultsMixin.defaultPaint
#80     RenderFlex.paint
#81     RenderObject._paintWithContext
#82     PaintingContext.paintChild
#83     RenderShiftedBox.paint
#84     RenderObject._paintWithContext
#85     PaintingContext.paintChild
#86     RenderProxyBoxMixin.paint
#87     RenderObject._paintWithContext
#88     PaintingContext.paintChild
#89     RenderProxyBoxMixin.paint
#90     _RenderInkFeatures.paint
#91     RenderObject._paintWithContext
#92     PaintingContext.paintChild
#93     RenderProxyBoxMixin.paint
#94     RenderCustomPaint.paint
#95     RenderObject._paintWithContext
#96     PaintingContext.paintChild
#97     RenderProxyBoxMixin.paint
#98     PaintingContext.pushLayer
#99     RenderPhysicalShape.paint
#100    RenderObject._paintWithContext
#101    PaintingContext.paintChild
#102    RenderShiftedBox.paint
#103    RenderObject._paintWithContext
#104    PaintingContext.paintChild
#105    RenderProxyBoxMixin.paint
#106    RenderObject._paintWithContext
#107    PaintingContext.paintChild
#108    RenderProxyBoxMixin.paint
#109    RenderObject._paintWithContext
#110    PaintingContext.paintChild
#111    RenderProxyBoxMixin.paint
#112    RenderObject._paintWithContext
#113    PaintingContext.paintChild
#114    RenderProxyBoxMixin.paint
#115    RenderObject._paintWithContext
#116    PaintingContext.paintChild
#117    RenderProxyBoxMixin.paint
#118    RenderObject._paintWithContext
#119    PaintingContext.paintChild
#120    RenderProxyBoxMixin.paint
#121    PaintingContext.pushLayer
#122    PaintingContext.pushTransform
#123    RenderTransform.paint
#124    RenderObject._paintWithContext
#125    PaintingContext.paintChild
#126    RenderProxyBoxMixin.paint
#127    RenderObject._paintWithContext
#128    PaintingContext.paintChild
#129    RenderBoxContainerDefaultsMixin.defaultPaint
#130    RenderStack.paintStack
#131    RenderStack.paint
#132    RenderObject._paintWithContext
#133    PaintingContext.paintChild
#134    RenderProxyBoxMixin.paint
#135    RenderObject._paintWithContext
#136    PaintingContext.paintChild
#137    RenderProxyBoxMixin.paint
#138    RenderObject._paintWithContext
#139    PaintingContext._repaintCompositedChild
#140    PaintingContext.repaintCompositedChild
#141    PaintingContext._compositeChild
#142    PaintingContext.paintChild
#143    RenderProxyBoxMixin.paint
#144    RenderObject._paintWithContext
#145    PaintingContext.paintChild
#146    RenderProxyBoxMixin.paint
#147    RenderObject._paintWithContext
#148    PaintingContext.paintChild
#149    RenderProxyBoxMixin.paint
#150    RenderObject._paintWithContext
#151    PaintingContext.paintChild
#152    RenderProxyBoxMixin.paint
#153    RenderObject._paintWithContext
#154    PaintingContext.paintChild
#155    RenderProxyBoxMixin.paint
#156    RenderObject._paintWithContext
#157    PaintingContext.paintChild
#158    RenderProxyBoxMixin.paint
#159    RenderObject._paintWithContext
#160    PaintingContext.paintChild
#161    RenderBoxContainerDefaultsMixin.defaultPaint
#162    RenderFlex.paint
#163    RenderObject._paintWithContext
#164    PaintingContext.paintChild
#165    RenderSliverMultiBoxAdaptor.paint
#166    RenderObject._paintWithContext
#167    PaintingContext.paintChild
#168    RenderViewportBase._paintContents
#169    PaintingContext.pushLayer
#170    PaintingContext.pushClipRect
#171    RenderViewportBase.paint
#172    RenderObject._paintWithContext
#173    PaintingContext._repaintCompositedChild
#174    PaintingContext.repaintCompositedChild
#175    PaintingContext._compositeChild
#176    PaintingContext.paintChild
#177    RenderProxyBoxMixin.paint
#178    RenderObject._paintWithContext
#179    PaintingContext.paintChild
#180    RenderProxyBoxMixin.paint
#181    RenderObject._paintWithContext
#182    PaintingContext.paintChild
#183    RenderProxyBoxMixin.paint
#184    RenderObject._paintWithContext
#185    PaintingContext.paintChild
#186    RenderProxyBoxMixin.paint
#187    RenderObject._paintWithContext
#188    PaintingContext.paintChild
#189    RenderProxyBoxMixin.paint
#190    RenderObject._paintWithContext
#191    PaintingContext.paintChild
#192    RenderProxyBoxMixin.paint
#193    RenderObject._paintWithContext
#194    PaintingContext.paintChild
#195    RenderProxyBoxMixin.paint
#196    RenderObject._paintWithContext
#197    PaintingContext.paintChild
#198    RenderProxyBoxMixin.paint
#199    RenderObject._paintWithContext
#200    PaintingContext.paintChild
#201    RenderBoxContainerDefaultsMixin.defaultPaint
#202    RenderCustomMultiChildLayoutBox.paint
#203    RenderObject._paintWithContext
#204    PaintingContext.paintChild
#205    RenderProxyBoxMixin.paint
#206    _RenderInkFeatures.paint
#207    RenderObject._paintWithContext
#208    PaintingContext.paintChild
#209    RenderProxyBoxMixin.paint
#210    PaintingContext.pushLayer
#211    RenderPhysicalModel.paint
#212    RenderObject._paintWithContext
#213    PaintingContext.paintChild
#214    RenderProxyBoxMixin.paint
#215    RenderObject._paintWithContext
#216    PaintingContext.paintChild
#217    RenderProxyBoxMixin.paint
#218    RenderObject._paintWithContext
#219    PaintingContext._repaintCompositedChild
#220    PaintingContext.repaintCompositedChild
#221    PaintingContext._compositeChild
#222    PaintingContext.paintChild
#223    RenderProxyBoxMixin.paint
#224    RenderObject._paintWithContext
#225    PaintingContext.paintChild
#226    RenderAnimatedOpacityMixin.paint
#227    RenderObject._paintWithContext
#228    PaintingContext.paintChild
#229    RenderProxyBoxMixin.paint
#230    RenderFractionalTranslation.paint
#231    RenderObject._paintWithContext
#232    PaintingContext.paintChild
#233    RenderProxyBoxMixin.paint
#234    RenderObject._paintWithContext
#235    PaintingContext._repaintCompositedChild
#236    PaintingContext.repaintCompositedChild
#237    PaintingContext._compositeChild
#238    PaintingContext.paintChild
#239    RenderProxyBoxMixin.paint
#240    RenderObject._paintWithContext
#241    PaintingContext.paintChild
#242    RenderProxyBoxMixin.paint
#243    RenderObject._paintWithContext
#244    PaintingContext.paintChild
#245    RenderProxyBoxMixin.paint
#246    RenderOffstage.paint
#247    RenderObject._paintWithContext
#248    PaintingContext.paintChild
#249    RenderProxyBoxMixin.paint
#250    RenderObject._paintWithContext
#251    PaintingContext.paintChild
#252    _RenderTheatre.paintStack
#253    _RenderTheatre.paint
#254    RenderObject._paintWithContext
#255    PaintingContext.paintChild
#256    RenderProxyBoxMixin.paint
#257    RenderObject._paintWithContext
#258    PaintingContext.paintChild
#259    RenderProxyBoxMixin.paint
#260    RenderObject._paintWithContext
#261    PaintingContext.paintChild
#262    RenderProxyBoxMixin.paint
#263    RenderObject._paintWithContext
#264    PaintingContext.paintChild
#265    RenderBoxContainerDefaultsMixin.defaultPaint
#266    RenderCustomMultiChildLayoutBox.paint
#267    RenderObject._paintWithContext
#268    PaintingContext.paintChild
#269    RenderProxyBoxMixin.paint
#270    _RenderInkFeatures.paint
#271    RenderObject._paintWithContext
#272    PaintingContext.paintChild
#273    RenderProxyBoxMixin.paint
#274    PaintingContext.pushLayer
#275    RenderPhysicalModel.paint
#276    RenderObject._paintWithContext
#277    PaintingContext.paintChild
#278    RenderProxyBoxMixin.paint
#279    RenderObject._paintWithContext
#280    PaintingContext.paintChild
#281    RenderProxyBoxMixin.paint
#282    RenderObject._paintWithContext
#283    PaintingContext._repaintCompositedChild
#284    PaintingContext.repaintCompositedChild
#285    PaintingContext._compositeChild
#286    PaintingContext.paintChild
#287    RenderProxyBoxMixin.paint
#288    RenderObject._paintWithContext
#289    PaintingContext.paintChild
#290    RenderAnimatedOpacityMixin.paint
#291    RenderObject._paintWithContext
#292    PaintingContext.paintChild
#293    RenderProxyBoxMixin.paint
#294    RenderFractionalTranslation.paint
#295    RenderObject._paintWithContext
#296    PaintingContext.paintChild
#297    RenderProxyBoxMixin.paint
#298    RenderObject._paintWithContext
#299    PaintingContext._repaintCompositedChild
#300    PaintingContext.repaintCompositedChild
#301    PaintingContext._compositeChild
#302    PaintingContext.paintChild
#303    RenderProxyBoxMixin.paint
#304    RenderObject._paintWithContext
#305    PaintingContext.paintChild
#306    RenderProxyBoxMixin.paint
#307    RenderObject._paintWithContext
#308    PaintingContext.paintChild
#309    RenderProxyBoxMixin.paint
#310    RenderOffstage.paint
#311    RenderObject._paintWithContext
#312    PaintingContext.paintChild
#313    RenderProxyBoxMixin.paint
#314    RenderObject._paintWithContext
#315    PaintingContext.paintChild
#316    _RenderTheatre.paintStack
#317    _RenderTheatre.paint
#318    RenderObject._paintWithContext
#319    PaintingContext.paintChild
#320    RenderProxyBoxMixin.paint
#321    RenderObject._paintWithContext
#322    PaintingContext.paintChild
#323    RenderProxyBoxMixin.paint
#324    RenderObject._paintWithContext
#325    PaintingContext.paintChild
#326    RenderProxyBoxMixin.paint
#327    RenderObject._paintWithContext
#328    PaintingContext.paintChild
#329    RenderProxyBoxMixin.paint
#330    RenderObject._paintWithContext
#331    PaintingContext.paintChild
#332    RenderProxyBoxMixin.paint
#333    RenderObject._paintWithContext
#334    PaintingContext.paintChild
#335    RenderProxyBoxMixin.paint
#336    RenderObject._paintWithContext
#337    PaintingContext.paintChild
#338    RenderProxyBoxMixin.paint
#339    RenderObject._paintWithContext
#340    PaintingContext.paintChild
#341    RenderView.paint
#342    RenderObject._paintWithContext
#343    PaintingContext._repaintCompositedChild
#344    PaintingContext.repaintCompositedChild
#345    PipelineOwner.flushPaint
#346    RendererBinding.drawFrame
#347    WidgetsBinding.drawFrame
#348    RendererBinding._handlePersistentFrameCallback
#349    SchedulerBinding._invokeFrameCallback
#350    SchedulerBinding.handleDrawFrame
#351    SchedulerBinding._handleDrawFrame
#355    _invoke (dart:ui/hooks.dart:166:10)
#356    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#357    _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#ae2bd relayoutBoundary=up2
RenderObject: RenderCustomPaint#ae2bd relayoutBoundary=up2
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=341.0, 0.0<=h<=116.0)
    size: Size(0.0, 0.0)
════════════════════════════════════════════════════════════════════════════════

```

**Comment by KKshitiz** [comment]
@Goncharo Hey, did you find a solution to this issue?

**Comment by Goncharo** [comment]
Unfortunately not. Turns out this happens sporadically with renders, irrespective of navigation.

I couldn't find a pattern to consistently reproduce this behaviour, and no amount of chart settings fidgeting helped.

**Comment by kazume** [comment]
We've been struggling with the same error for a bit now. We found that, for some reason, adding a new series will throw the error described above (related to the _getLegendItemCollection() method), while changing values and removing a series does not.
Giving the chart a UniqueKey solved the problem for us.
Seems that when not using a key (= reusing the "old" state), the value changes are reflected, but adding a series is not correctly configured in said old state.

**Comment by Goncharo** [comment]
@kazume Thanks for the `UniqueKey` suggestion, will give that a shot and see if it works!

**Comment by Goncharo** [comment]
@kazume

Looks like adding a `UniqueKey()` in the chart seems to work! Have been using the spline charts in our app for the past couple days, and the exception has not been thrown even a single time.

To be specific for anyone encountering this, simply build the chart widget as such:

```
    return SfCartesianChart(
      key: UniqueKey(),
          ...
    );
```

**Comment by kazume** [comment]
Resolved?

**Comment by adarshgoimedia** [comment]
Thanks a lot! adding uniquekey resolved the issue
