### ISSUE TITLE
Setting onMarkerRender has conflict with zoom and scroll

### ISSUE THREAD

**Issue by P-B1101** [syncfusion/flutter-widgets#461]
When I set zoomPanBehavior with autoScrollingDelta in primaryXAxis of 5 and if i have like 7 point to show and set onMarkerRender parameter, I got this error.

════════ Exception caught by rendering library ═════════════════════════════════
The following _CastError was thrown during paint():
Null check operator used on a null value
e:syncfusion_flutter_charts/…/common/marker.dart:337

This is my Code.

```
Widget _chart(
    MuscleProgressSuccessState progressState,
  ) =>
      (progressState.progress?.volumes.isEmpty ?? true)
          ? _emptyState
          : BlocBuilder<SettingsCubit, SettingsState>(
              builder: (context, mState) {
                final isDark = AppProvider.of(context).isDark;
                final gridColor = isDark
                    ? MyColors.darkChartGridLinesColor
                    : MyColors.chartGridLinesColor;
                final textColor = isDark
                    ? MyColors.darkChartTextColor
                    : MyColors.chartTextColor;
                final itemList = progressState.progress?.volumes ?? [];
                final items = itemList.sublist(
                  max(itemList.length - 7, 0),
                );
                final itemCounts = items.length;
                final feelings = progressState.progress?.feelings ?? [];
                return Container(
                  margin: const EdgeInsetsDirectional.only(
                    start: 16,
                    end: 24,
                    top: 24,
                    bottom: 16,
                  ),
                  width: double.infinity,
                  height: double.infinity,
                  child: SfCartesianChart(
                    key: UniqueKey(),
                    plotAreaBorderWidth: 0,
                    axisLabelFormatter: (details) {
                      final isY =
                          details.orientation == AxisOrientation.vertical;
                      final yValue = details.value
                          .toDouble()
                          .getWeight(mState.settings.metrics)
                          .toDouble()
                          .toNum;
                      return ChartAxisLabel(
                        isY ? yValue : details.actualText,
                        TextStyle(
                          color: textColor,
                          fontFamily: Fonts.alvarEssential,
                          fontSize: 12,
                          fontWeight: Fonts.regular,
                        ),
                      );
                    },
                    selectionType: SelectionType.point,
                    zoomPanBehavior: ZoomPanBehavior(
                      enablePanning: true,
                      enablePinching: true,
                      zoomMode: ZoomMode.x,
                      enableDoubleTapZooming: true,
                    ),
                    primaryXAxis: NumericAxis(
                      autoScrollingDelta: 5,
                      zoomFactor: .5,
                      zoomPosition: .5,
                      enableAutoIntervalOnZooming: true,
                      maximum: itemCounts.toDouble(),
                      axisLine: AxisLine(
                        width: 1,
                        color: gridColor,
                      ),
                      interval: 1,
                      majorGridLines: MajorGridLines(
                        width: 1,
                        color: gridColor,
                      ),
                      majorTickLines: MajorTickLines(
                        color: AppProvider.of(context).isDark
                            ? Theme.of(context).textTheme.bodyText1?.color
                            : MyColors.subtitleColor2,
                        size: 4,
                        width: 4,
                      ),
                    ),
                    primaryYAxis: NumericAxis(
                      isVisible: true,
                      majorGridLines: MajorGridLines(
                        color: gridColor,
                        width: 1,
                      ),
                      axisLine: AxisLine(
                        width: 1,
                        color: gridColor,
                      ),
                      majorTickLines: MajorTickLines(
                        color: AppProvider.of(context).isDark
                            ? Theme.of(context).textTheme.bodyText1?.color
                            : MyColors.subtitleColor2,
                        size: 0,
                        width: 0,
                      ),
                      minimum: (items.minValue * .8).roundToDouble(),
                      maximum: (items.maxValue * 1.25).roundToDouble(),
                    ),
                    trackballBehavior: TrackballBehavior(
                      enable: true,
                      markerSettings: const TrackballMarkerSettings(
                        color: Colors.transparent,
                        borderColor: Colors.transparent,
                        borderWidth: 5,
                        height: 11,
                        markerVisibility: TrackballVisibilityMode.visible,
                        width: 11,
                        shape: DataMarkerType.circle,
                      ),
                      activationMode: ActivationMode.singleTap,
                      shouldAlwaysShow: true,
                      lineDashArray: const [5, 5],
                      lineType: TrackballLineType.vertical,
                      lineWidth: 1,
                      tooltipSettings: InteractiveTooltip(
                        color: _mainColor(context),
                        borderColor: _mainColor(context),
                      ),
                      lineColor: _mainColor(context),
                      builder: (context, details) {
                        return BlocBuilder<WeightChartTouchCubit,
                            WeightChartTouchState>(
                          builder: (context, state) {
                            final intData = details.point?.y as int;
                            final initialIndex = details.point?.x;
                            final String feelingStr;
                            if (initialIndex == null ||
                                initialIndex is! int ||
                                feelings.isEmpty) {
                              feelingStr = '';
                            } else {
                              int index =
                                  min(feelings.length, initialIndex - 1);
                              index = max(0, index);
                              final feeling = feelings[index];
                              feelingStr = _titles(context)[feeling];
                            }

                            return Container(
                              padding: const EdgeInsets.only(
                                left: 12,
                                right: 12,
                                top: 4,
                                bottom: 4,
                              ),
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(5),
                                border: Border.all(
                                  width: 1,
                                  color: _mainColor(context),
                                ),
                                color: Theme.of(context).cardColor,
                              ),
                              child: Text.rich(
                                TextSpan(
                                  style: TextStyle(
                                    fontFamily: Fonts.alvarEssential,
                                    fontWeight: Fonts.regular,
                                    color: AppProvider.of(context).isDark
                                        ? Theme.of(context)
                                            .textTheme
                                            .bodyText1
                                            ?.color
                                        : MyColors.subtitleColor2,
                                  ),
                                  children: [
                                    if (feelingStr.isNotEmpty)
                                      TextSpan(
                                        text: '$feelingStr\n',
                                        style: const TextStyle(
                                          fontSize: 13,
                                        ),
                                      ),
                                    TextSpan(
                                      text: intData
                                          .toDouble()
                                          .getWeight(mState.settings.metrics)
                                          .toDouble()
                                          .toNum,
                                      style: const TextStyle(
                                        fontSize: 15,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            );
                          },
                        );
                      },
                      tooltipDisplayMode: TrackballDisplayMode.nearestPoint,
                    ),
                    tooltipBehavior: TooltipBehavior(
                      enable: false,
                    ),
                    onMarkerRender: (args) {
                      final initialIndex = args.pointIndex ?? -1;
                      final int feelingIndex;
                      if (feelings.isEmpty) {
                        feelingIndex = -1;
                      } else {
                        int index = min(feelings.length, initialIndex);
                        index = max(0, index);
                        final feeling = feelings[index];
                        feelingIndex = feeling;
                      }
                      if (feelingIndex >= 1 && feelingIndex <= 5) {
                        args.color = _getMarkerColor(context, feelingIndex);
                      }
                    },
                    series: [
                      AreaSeries<int, int>(
                        enableTooltip: true,
                        markerSettings: MarkerSettings(
                          isVisible: true,
                          color: _mainColor(context),
                          borderColor: isDark
                              ? Theme.of(context).textTheme.bodyText1?.color
                              : MyColors.subtitleColor2,
                          borderWidth: 3,
                          height: 14,
                          width: 14,
                          shape: DataMarkerType.circle,
                        ),
                        dataSource: items,
                        xValueMapper: (int weight, _) => _ + 1,
                        yValueMapper: (int weight, _) => weight,
                        borderDrawMode: BorderDrawMode.top,
                        borderWidth: 4,
                        gradient: LinearGradient(
                          colors: [
                            _mainColor(context).withOpacity(.8),
                            _mainColor(context).withOpacity(0)
                          ],
                          begin: Alignment.topCenter,
                          end: Alignment.bottomCenter,
                          stops: const [.25, 1],
                        ),
                        borderColor: _mainColor(context),
                      ),
                    ],
                  ),
                );
              },
            );

  Widget get _emptyState => Builder(
        builder: (context) {
          final isDark = AppProvider.of(context).isDark;
          final gridColor = isDark
              ? MyColors.darkChartGridLinesColor
              : MyColors.chartGridLinesColor;
          final textColor =
              isDark ? MyColors.darkChartTextColor : MyColors.chartTextColor;
          final items = [0, 0, 0, 0, 0, 0, 0];
          final itemCounts = items.length;
          return Container(
            margin: const EdgeInsetsDirectional.only(
              start: 16,
              end: 24,
              top: 32,
              bottom: 16,
            ),
            width: double.infinity,
            height: double.infinity,
            child: Blur(
              blur: 2,
              alignment: Alignment.center,
              blurColor: Theme.of(context).backgroundColor,
              overlay: Builder(
                builder: (context) => Center(
                  child: MyText(
                    text: AppLocalizations.of(context)!.empty_chart_data,
                    fontSize: 20,
                    fontWeight: Fonts.medium,
                  ),
                ),
              ),
              child: SfCartesianChart(
                plotAreaBorderWidth: 0,
                axisLabelFormatter: (details) => ChartAxisLabel(
                  details.actualText,
                  TextStyle(
                    color: textColor,
                    fontFamily: Fonts.alvarEssential,
                    fontSize: 12,
                    fontWeight: Fonts.regular,
                  ),
                ),
                selectionType: SelectionType.point,
                primaryXAxis: NumericAxis(
                  maximum: itemCounts + _xInterval * .2,
                  axisLine: AxisLine(
                    width: 1,
                    color: gridColor,
                  ),
                  interval: 1,
                  majorGridLines: MajorGridLines(
                    width: 1,
                    color: gridColor,
                  ),
                  majorTickLines: MajorTickLines(
                    color: AppProvider.of(context).isDark
                        ? Theme.of(context).textTheme.bodyText1?.color
                        : MyColors.subtitleColor2,
                    size: 4,
                    width: 4,
                  ),
                ),
                primaryYAxis: NumericAxis(
                  isVisible: true,
                  majorGridLines: MajorGridLines(
                    color: gridColor,
                    width: 1,
                  ),
                  axisLine: AxisLine(
                    width: 1,
                    color: gridColor,
                  ),
                  majorTickLines: MajorTickLines(
                    color: AppProvider.of(context).isDark
                        ? Theme.of(context).textTheme.bodyText1?.color
                        : MyColors.subtitleColor2,
                    size: 0,
                    width: 0,
                  ),
                  minimum: (items.minValue * .8).roundToDouble(),
                  maximum: (items.maxValue * 1.25).roundToDouble(),
                ),
                trackballBehavior: TrackballBehavior(
                  enable: true,
                  activationMode: ActivationMode.singleTap,
                  shouldAlwaysShow: true,
                  lineDashArray: const [5, 5],
                  lineType: TrackballLineType.vertical,
                  lineWidth: 1,
                  tooltipSettings: InteractiveTooltip(
                    color: _mainColor(context),
                    borderColor: _mainColor(context),
                  ),
                  lineColor: _mainColor(context),
                  builder: (context, details) {
                    return BlocBuilder<SettingsCubit, SettingsState>(
                      builder: (context, mState) => BlocBuilder<
                          WeightChartTouchCubit, WeightChartTouchState>(
                        builder: (context, state) {
                          final intData = details.point?.y as int;
                          return Container(
                            padding: const EdgeInsets.only(
                              left: 12,
                              right: 12,
                              top: 4,
                              bottom: 4,
                            ),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(5),
                              border: Border.all(
                                width: 1,
                                color: _mainColor(context),
                              ),
                              color: Theme.of(context).cardColor,
                            ),
                            child: Text.rich(
                              TextSpan(
                                style: TextStyle(
                                  fontFamily: Fonts.alvarEssential,
                                  fontWeight: Fonts.regular,
                                  color: AppProvider.of(context).isDark
                                      ? Theme.of(context)
                                          .textTheme
                                          .bodyText1
                                          ?.color
                                      : MyColors.subtitleColor2,
                                ),
                                children: [
                                  TextSpan(
                                    text: intData
                                        .toDouble()
                                        .getWeight(mState.settings.metrics)
                                        .toDouble()
                                        .toNum,
                                    style: const TextStyle(
                                      fontSize: 15,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          );
                        },
                      ),
                    );
                  },
                  tooltipDisplayMode: TrackballDisplayMode.nearestPoint,
                ),
                tooltipBehavior: TooltipBehavior(
                  enable: false,
                ),
                series: [
                  AreaSeries<int, int>(
                    dataSource: items,
                    xValueMapper: (int weight, _) => _ + 1,
                    yValueMapper: (int weight, _) => weight,
                  ),
                ],
              ),
            ),
          );
        },
      );

  double get _xInterval => 1;

  Color _mainColor(BuildContext context) => AppProvider.of(context).isDark
      ? MyColors.darkMentalColor
      : MyColors.mentalColor;

  Color? _getMarkerColor(BuildContext context, int index) {
    switch (index) {
      case 0:
        return AppProvider.of(context).isDark
            ? MyColors.darkVeryEasy
            : MyColors.veryEasy;
      case 1:
        return AppProvider.of(context).isDark
            ? MyColors.darkEasy
            : MyColors.easy;
      case 2:
        return AppProvider.of(context).isDark
            ? MyColors.darkModerate
            : MyColors.moderate;
      case 3:
        return AppProvider.of(context).isDark
            ? MyColors.darkHard
            : MyColors.hard;
      case 4:
        return AppProvider.of(context).isDark
            ? MyColors.darkVeryHard
            : MyColors.veryHard;
      default:
        return AppProvider.of(context).isDark
            ? Theme.of(context).textTheme.bodyText1?.color
            : MyColors.subtitleColor2;
    }
  }

  List<String> _titles(BuildContext context) => [
        AppLocalizations.of(context)!.very_easy_label,
        AppLocalizations.of(context)!.easy_label,
        AppLocalizations.of(context)!.moderate_label,
        AppLocalizations.of(context)!.hard_label,
        AppLocalizations.of(context)!.very_hard_label,
      ];
```

Full Error Log

> #15     SchedulerBinding._invokeFrameCallback
> package:flutter/…/scheduler/binding.dart:1143
> #16     SchedulerBinding.handleDrawFrame
> package:flutter/…/scheduler/binding.dart:1080
> #17     SchedulerBinding._handleDrawFrame
> package:flutter/…/scheduler/binding.dart:996
> #21     _invoke (dart:ui/hooks.dart:166:10)
> #22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
> #23     _drawFrame (dart:ui/hooks.dart:129:31)
> (elided 3 frames from dart:async)
> The following RenderObject was being processed when the exception was fired: RenderCustomPaint#1d340 relayoutBoundary=up2
> RenderObject: RenderCustomPaint#1d340 relayoutBoundary=up2
>     parentData: <none> (can use size)
>     constraints: BoxConstraints(0.0<=w<=351.4, 0.0<=h<=330.0)
>     size: Size(0.0, 0.0)
> ════════════════════════════════════════════════════════════════════════════════
>

**Comment by SriramKiranSenthilkumar** [comment]
Hi @P-B1101,

Greetings from Syncfusion. We have analyzed your scenario at our end and we would like to let you know the reported issue regarding the **onMarkerRender** event throwing exception when the chart is zooming with auto-scrolling feature enabled is already fixed at our end and the changes will be included in our upcoming weekly patch release which is expected to be rolled out by 30th November 2021(tomorrow). We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by P-B1101** [comment]
Thanks a lot :)

**Comment by P-B1101** [comment]
@SriramKiranSenthilkumar Thanks for the update. there is no error anymore. but there is a problem and that is after the initial render every marker has its own color (as desired) but after scrolling the chart, all colors back to what that set in Series `MarkerSettings`!!!

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @P-B1101 

We have analyzed your query and we have tried to reproduce the reported issue regarding marker color is changing when scrolling the chart. But the reported issue is not reproduced at our end, the marker color is set properly based on the event after panning. We have also attached the sample, which is used in the test phase, and since the scenario is not replicated at our end, kindly try to replicate the issue in the below attached sample it will help us to provide a solution sooner.

Sample:  [github_461.zip](https://github.com/syncfusion/flutter-widgets/files/7642429/github_461.zip)

Video record: https://user-images.githubusercontent.com/61863686/144435362-946f6f74-329d-4d36-8a28-361e5f667347.mp4



Regards,
Yuvaraj.

**Comment by P-B1101** [comment]
I'll see the sample app asap and report the result.
Thanks again for your response.

**Comment by P-B1101** [comment]
Hi Again.
I just modify your sample app main.dart to reproduce the issue.

```
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const Center(
        child: _MyChartWidget(),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class YourChartWidget extends StatelessWidget {
  const YourChartWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      zoomPanBehavior:
          ZoomPanBehavior(enablePanning: true, enablePinching: true),
      onMarkerRender: (MarkerRenderArgs args) {
        print('this is your test...');
        args.color = Colors.yellow;
        args.borderColor = Colors.red;
        args.borderWidth = 2;
      },
      primaryXAxis: NumericAxis(
        visibleMaximum: 7,
        visibleMinimum: 4,
      ),
      primaryYAxis: NumericAxis(),
      series: <ChartSeries<ChartData, num>>[
        LineSeries<ChartData, num>(
          dataSource: <ChartData>[
            ChartData(1, 10),
            ChartData(2, 30),
            ChartData(3, 20),
            ChartData(4, 50),
            ChartData(5, 40),
            ChartData(6, 70),
            ChartData(7, 40),
            ChartData(8, 30),
            ChartData(9, 10),
            ChartData(10, 20),
          ],
          markerSettings: const MarkerSettings(
              isVisible: true,
              color: Colors.blue,
              borderColor: Colors.green,
              borderWidth: 2),
          xValueMapper: (ChartData data, _) => data.x,
          yValueMapper: (ChartData data, _) => data.y,
        )
      ],
    );
  }
}

class ChartData {
  ChartData(this.x, this.y);
  final num x;
  final num y;
}

class _MyChartWidget extends StatelessWidget {
  const _MyChartWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Builder(
      builder: (context) {
        final itemCounts = items.length;
        return Container(
          margin: const EdgeInsetsDirectional.only(
            start: 16,
            end: 24,
            top: 24,
            bottom: 16,
          ),
          width: double.infinity,
          height: double.infinity,
          child: SfCartesianChart(
            plotAreaBorderWidth: 0,
            axisLabelFormatter: (details) {
              final isY = details.orientation == AxisOrientation.vertical;
              final yValue = details.value.toString();
              return ChartAxisLabel(
                isY ? yValue : details.actualText,
                const TextStyle(
                  fontSize: 12,
                ),
              );
            },
            selectionType: SelectionType.point,
            zoomPanBehavior: ZoomPanBehavior(
              enablePanning: true,
              enablePinching: true,
              zoomMode: ZoomMode.x,
              enableDoubleTapZooming: true,
            ),
            primaryXAxis: NumericAxis(
              visibleMaximum: 7,
              visibleMinimum: 4,
              autoScrollingDelta: 5,
              zoomFactor: .5,
              zoomPosition: .5,
              enableAutoIntervalOnZooming: true,
              maximum: itemCounts.toDouble(),
              axisLine: const AxisLine(
                width: 1,
              ),
              interval: 1,
              majorGridLines: const MajorGridLines(
                width: 1,
              ),
              majorTickLines: const MajorTickLines(
                size: 4,
                width: 4,
              ),
            ),
            primaryYAxis: NumericAxis(
              isVisible: true,
              majorGridLines: const MajorGridLines(
                width: 1,
              ),
              axisLine: const AxisLine(
                width: 1,
              ),
              majorTickLines: const MajorTickLines(
                size: 0,
                width: 0,
              ),
            ),
            trackballBehavior: TrackballBehavior(
              enable: true,
              markerSettings: const TrackballMarkerSettings(
                color: Colors.transparent,
                borderColor: Colors.transparent,
                borderWidth: 5,
                height: 11,
                markerVisibility: TrackballVisibilityMode.visible,
                width: 11,
                shape: DataMarkerType.circle,
              ),
              activationMode: ActivationMode.singleTap,
              shouldAlwaysShow: true,
              lineDashArray: const [5, 5],
              lineType: TrackballLineType.vertical,
              lineWidth: 1,
              tooltipSettings: const InteractiveTooltip(),
              builder: (context, details) {
                return Builder(
                  builder: (context) {
                    final intData = details.point?.y as int;
                    final initialIndex = details.point?.x;
                    final String feelingStr;
                    if (initialIndex == null ||
                        initialIndex is! int ||
                        feelings.isEmpty) {
                      feelingStr = '';
                    } else {
                      int index = min(feelings.length, initialIndex - 1);
                      index = max(0, index);
                      final feeling = feelings[index] - 1;
                      feelingStr = _titles(context)[feeling];
                    }

                    return Container(
                      padding: const EdgeInsets.only(
                        left: 12,
                        right: 12,
                        top: 4,
                        bottom: 4,
                      ),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(5),
                        border: Border.all(
                          width: 1,
                        ),
                        color: Theme.of(context).cardColor,
                      ),
                      child: Text.rich(
                        TextSpan(
                          style: const TextStyle(),
                          children: [
                            if (feelingStr.isNotEmpty)
                              TextSpan(
                                text: '$feelingStr\n',
                                style: const TextStyle(
                                  fontSize: 13,
                                ),
                              ),
                            TextSpan(
                              text: intData.toString(),
                              style: const TextStyle(
                                fontSize: 15,
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                );
              },
              tooltipDisplayMode: TrackballDisplayMode.nearestPoint,
            ),
            tooltipBehavior: TooltipBehavior(
              enable: false,
            ),
            onMarkerRender: (args) {
              print('this is a test...');
              final initialIndex = args.pointIndex ?? -1;
              if (feelings.isEmpty || initialIndex == -1) return;
              int index = min(feelings.length, initialIndex);
              final feeling = feelings[index];
              if (feeling >= 1 && feeling <= 5) {
                args.color = _getMarkerColor(context, feeling);
              }
            },
            series: [
              AreaSeries<int, int>(
                enableTooltip: true,
                markerSettings: MarkerSettings(
                  isVisible: true,
                  borderColor: Theme.of(context).textTheme.bodyText1?.color,
                  borderWidth: 3,
                  height: 14,
                  width: 14,
                  shape: DataMarkerType.circle,
                ),
                dataSource: items,
                xValueMapper: (int weight, _) => _ + 1,
                yValueMapper: (int weight, _) => weight,
                borderDrawMode: BorderDrawMode.top,
                borderWidth: 4,
              ),
            ],
          ),
        );
      },
    );
  }
}

Color? _getMarkerColor(BuildContext context, int index) {
  switch (index) {
    case 1:
      return Colors.lightBlueAccent;
    case 2:
      return Colors.blue;
    case 3:
      return Colors.green;
    case 4:
      return Colors.orange;
    case 5:
      return Colors.red;
    default:
      return Theme.of(context).textTheme.bodyText1?.color;
  }
}

List<String> _titles(BuildContext context) => [
      'very easy',
      'easy',
      'moderate',
      'hard',
      'very hard',
    ];

final items = [
  10,
  30,
  20,
  50,
  40,
  70,
  40,
  30,
  10,
  20,
];

final feelings = [
  4,
  2,
  3,
  2,
  5,
  1,
  2,
  3,
  1,
  4,
];


```

what am i doing wrong!!! :((

**Comment by P-B1101** [comment]
I found the problem. 

```
                      markerSettings: const TrackballMarkerSettings(
                        color: Colors.transparent,
                        borderColor: Colors.transparent,
                        borderWidth: 5,
                        height: 11,
                        markerVisibility: TrackballVisibilityMode.visible,
                        width: 11,
                        shape: DataMarkerType.circle,
                      ),
```

removing this part of code will fix the issue.
it seems TrackballMarker render on top of original marker on every point.
