### ISSUE TITLE
"RangeError (index): Invalid value: Valid value range is empty: 0" while accidentally zooming way into the graph then trying to pinch zoom out

### ISSUE THREAD

**Issue by MrCsabaToth** [syncfusion/flutter-widgets#465]
I reproduced this multiple times with the original sample code of the #463 
What's happening is that I accidentally zoom due to a swipe up gesture transforming into an area zoom in, the chart is in ZoomMode.x and since it's a wipe up the x domain for zooming in is very tiny. The zoom happens, and as soon as I try to zoom out with a pinch gesture the crash happens. It requires a few times to try, here is a video: https://youtu.be/JWoRxBEvih0

```
======== Exception caught by gesture library =======================================================
The following RangeError was thrown while dispatching a pointer event:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      getNearestChartPoints (package:syncfusion_flutter_charts/src/chart/common/common.dart:1653:28)
#2      TrackballRenderingDetails.generateAllPoints (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:897:13)
#3      TrackballBehavior.show (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:436:36)
#4      TrackballBehaviorRenderer.onTouchDown (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:562:52)
#5      ContainerArea._performPointerDown (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2988:14)
#6      ContainerArea.build.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2197:21)
#7      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2882:29)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#9      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#10     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#11     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#17     _invoke1 (dart:ui/hooks.dart:185:10)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Event: PointerDownEvent#6fbfb(position: Offset(343.9, 312.0))
  position: Offset(343.9, 312.0)
Target: RenderPointerListener#b110b
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=384.0, h=418.7)
  size: Size(384.0, 418.7)
  behavior: deferToChild
  listeners: down, move, up, signal
====================================================================================================
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @MrCsabaToth 

Greetings from Syncfusion. We have analyzed your query and we have tried to reproduce the reported issue regarding getting a range error exception when pinch-zoom out the chart. The reported issue is getting reproduced at our end. We have considered this as a bug, and it will be fixed and rolled out in our weekly patch release expected on 7th Dec 2021.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @MrCsabaToth 

Thanks for the patience. The reported issue regarding getting a range error exception when zooming out the chart has been fixed and rolled out in our weekly patch release. To resolve this, kindly upgrade the chart widget package to the latest version below. 

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.3.57

Regards,
Yuvaraj.
