### ISSUE TITLE
[19.4.41] [Range Slider] app throws error when SfRangeValues is same number

### ISSUE THREAD

**Issue by ImTung** [syncfusion/flutter-widgets#526]
Hi!
Here is my setting:
```
SfRangeSlider(
  values: _currentValue,
  min: _minNumber,
  max: _maxNumber,
  showTicks: true,
  showLabels: true,
  enableTooltip: true,
  interval: 1,
  stepSize: 1,
  onChanged: (SfRangeValues values) {},
)
```

When I set _currentValue is not the same number, it works. But when I changed to the same number (ex: start: 2.0-2.0),
I drag and it throws an error:

```
[log] Null check operator used on a null value
[log] 
#0      RenderBaseRangeSlider._updateRangeValues      package:syncfusion_flutter_sliders/src/range_slider_base.dart:488
#1      RenderBaseRangeSlider._onDragUpdate     package:syncfusion_flutter_sliders/src/range_slider_base.dart:327
#2      DragGestureRecognizer._checkUpdate.<anonymous closure>      package:flutter/…/gestures/monodrag.dart:449
#3      GestureRecognizer.invokeCallback      package:flutter/…/gestures/recognizer.dart:198
#4      DragGestureRecognizer._checkUpdate      package:flutter/…/gestures/monodrag.dart:449
#5      DragGestureRecognizer.handleEvent     package:flutter/…/gestures/monodrag.dart:298
#6      PointerRouter._dispatch     package:flutter/…/gestures/pointer_router.dart:94
#7      PointerRouter._dispatchEventToRoutes.<anonymous closure>      package:flutter/…/gestures/pointer_router.dart:139
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)     #9      PointerRouter._dispatchEventToRoutes    package:flutter/…/gestures/pointer_router.dart:137
#10     PointerRouter.route     package:flutter/…/gestures/pointer_router.dart:123
#11     GestureBinding.handleEvent      package:flutter/…/gestures/binding.dart:439
#12     GestureBinding.dispatchEvent      package:flutter/…/gestures/binding.dart:419
#13     RendererBinding.dispatchEvent     package:flutter/…/rendering/binding.dart:322
#14     GestureBinding._handlePointerEventImmediately     package:flutter/…/gestures/binding.dart:374
#15     GestureBinding.handlePointerEvent     package:flutter/…/gestures/binding.dart:338
#16     GestureBinding._flushPointerEventQueue      package:flutter/…/gestures/binding.dart:296
#17     GestureBinding._handlePointerDataPacket     package:flutter/…/gestures/binding.dart:279
#18     _rootRunUnary (dart:async/zone.dart:1444:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#21     _invoke1 (dart:ui/hooks.dart:169:10)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)

```

**Comment by PraveenGopalsamy** [comment]
Hi ImTung,

We can reproduce the reported issue at our end, and the fix will be included in the weekly release which will be available on January 18, 2022. You can track the status of the bug from below link.

**Feedback Link:** https://www.syncfusion.com/feedback/31779/app-throws-null-exception-when-sfrangevalues-are-same-in-range-slider

We will notify you once the issue is fixed and rolled out in our release and we appreciate your patience until then.
 
Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi ImTung, 

We are glad to announce that our weekly release was rolled out and the fix for the "Exception thrown when dragging the RangeSlider with same values" was included in the weekly release. 

**Release Version:** [19.4.43](https://pub.dev/packages/syncfusion_flutter_sliders/versions/19.4.43)

We thank you for your continuous support in helping us improve the quality of our products and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

**Comment by ImTung** [comment]
Hi @PraveenGopalsamy,
just upgraded to the new version, it's worked perfectly.
Thanks
