### ISSUE TITLE
Using SfRangeSlider in showBottomSheet() results in Null check operator used on a null value

### ISSUE THREAD

**Issue by ahuang11** [syncfusion/flutter-widgets#551]
To reproduce:
```
showBottomSheet(
                      enableDrag: false,
                      backgroundColor: Colors.black,
                      context: context,
                      builder: (context) {
                        return filterModal;
                      },
                    )
```

```

class FilterModal extends StatefulWidget {
  @override
  State<FilterModal> createState() => _FilterModalState();
}

class _FilterModalState extends State<FilterModal> {
  SfRangeValues _values = SfRangeValues(40.0, 80.0);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.symmetric(horizontal: 25),
      child: Wrap(
        children: [
          SfRangeSlider(
            min: 0.0,
            max: 100.0,
            values: _values,
            interval: 20,
            showTicks: true,
            showLabels: true,
            enableTooltip: true,
            minorTicksPerInterval: 1,
            onChanged: (SfRangeValues values) {
              setState(() {
                _values = values;
              });
            },
          ),
          SizedBox(height: 100),
        ],
      ),
    );
  }
}
```

Errors:
```
SfRangeSlider(
  ├─values: SfRangeValues#c7a68
      start: 40.0
      end: 80.0
  , min: 0.0, max: 100.0, interval: 20.0, stepSize: null, minorTicksPerInterval: 1, Ticks are showing, Labels are showing, Dividers are not showing, Tooltip is enabled, Interval selection is disabled, activeColor: null, inactiveColor: null, labelPlacement: onTicks, numberFormat: null, dateIntervalType: null, dirty, dependencies: [Directionality, _LocalizationsScope-[GlobalKey#20946], _InheritedTheme], state: _SfRangeSliderState#fbddb(tickers: tracking 7 tickers)):
Null check operator used on a null value

The relevant error-causing widget was: 
  SfRangeSlider SfRangeSlider:file:///Users/airbook/Applications/Developer/apps/name_fame/lib/widgets/modal.dart:107:11
When the exception was thrown, this was the stack: 
#0      _SfRangeSliderState._getRangeSliderThemeData (package:syncfusion_flutter_sliders/src/range_slider.dart:1416:57)
#1      _SfRangeSliderState.build (package:syncfusion_flutter_sliders/src/range_slider.dart:1619:29)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4856:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4740:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4914:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4463:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4946:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3487:15)
#8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5773:32)
#9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6431:17)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3487:15)
#11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6277:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3487:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4766:16)
#14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4914:11)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4463:5)
#16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2666:19)
#17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#18     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#19     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#20     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#21     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
```

**Comment by SuryaChinnadurai** [comment]
Hi ahuang11

We have checked the mentioned issue from our side. But we are unable to reproduce this issue at our end. Attached code snippet that we have tried for your reference. Please check this code example and if the issue still persists at your end, then please modify the code example and send us back. So that we can further proceed with the issue. 

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Builder(
        builder: (context) => Align(
          alignment: Alignment.bottomRight,
          child: FloatingActionButton(
            onPressed: () {
              showBottomSheet(
                  backgroundColor: Colors.black,
                  context: context,
                  builder: (context) => const FilterModal());
            },
          ),
        ),
      ),
    );
  }
```

```
class FilterModal extends StatefulWidget {
  const FilterModal({Key? key}) : super(key: key);

  @override
  State<FilterModal> createState() => _FilterModalState();
}

class _FilterModalState extends State<FilterModal> {
  SfRangeValues _values = const SfRangeValues(40.0, 80.0);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 25),
      child: Wrap(
        children: [
          SfRangeSlider(
            min: 0.0,
            max: 100.0,
            values: _values,
            interval: 20,
            showTicks: true,
            showLabels: true,
            enableTooltip: true,
            minorTicksPerInterval: 1,
            onChanged: (SfRangeValues values) {
              setState(() {
                _values = values;
              });
            },
          ),
          const SizedBox(height: 100),
        ],
      ),
    );
  }
}
```
Please let us know if you need any further assistance in this. 
 
Regards, 
Surya C.

**Comment by kartik1225** [comment]
I am also having the same issue 

### version
syncfusion_flutter_sliders: `^19.4.47`

### Code
```
SfSlider(
    value: 0.5,
    onChanged: (value) {},
)
```

### Error
```
The following _CastError was thrown building SfSlider(value: 0.5, min: 0.0, max: 1.0, interval: null, stepSize: null, minorTicksPerInterval: 0, Ticks are not showing, Labels are not showing, Dividers are not showing, Tooltip is disabled, activeColor: null, inactiveColor: null, labelPlacement: onTicks, numberFormat: null, dateIntervalType: null, dirty, dependencies: [_InheritedTheme, _EffectiveTickerMode, _LocalizationsScope-[GlobalKey#b4ca6], Directionality], state: _SfSliderState#d09c5(tickers: tracking 3 tickers)):
Null check operator used on a null value

The relevant error-causing widget was: 
  SfSlider SfSlider:file:///Users/kartik/Code/pilot/remux_convert/remux_convert/lib/ui/converter_screen/convert_config_card/audio_options.dart:93:26
When the exception was thrown, this was the stack: 
#0      _SfSliderState._getSliderThemeData (package:syncfusion_flutter_sliders/src/slider.dart:1262:57)
#1      _SfSliderState.build (package:syncfusion_flutter_sliders/src/slider.dart:1436:26)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4754:11)
```

**Comment by ahuang11** [comment]
Thank you Surya for your quick reply (and sorry for my late response).

I was able to run your minimal example, and even a more complicated example derived from my main app:
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_sliders/sliders.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(child: Column(children: [SearchTextField()])));
  }
}

class SearchTextField extends StatefulWidget {
  @override
  _SearchTextFieldState createState() => _SearchTextFieldState();
}

class _SearchTextFieldState extends State<SearchTextField> {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.bottomCenter,
      child: TextField(
        textCapitalization: TextCapitalization.words,
        decoration: InputDecoration(
          suffixIcon: Padding(
            padding: EdgeInsets.symmetric(horizontal: 8),
            child: Wrap(
              children: [
                IconButton(
                  icon: const Icon(Icons.filter_alt),
                  onPressed: () {
                    showBottomSheet(
                        backgroundColor: Colors.black,
                        context: context,
                        builder: (context) => const FilterModal());
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class FilterModal extends StatefulWidget {
  const FilterModal({Key? key}) : super(key: key);

  @override
  State<FilterModal> createState() => _FilterModalState();
}

class _FilterModalState extends State<FilterModal> {
  SfRangeValues _values = const SfRangeValues(40.0, 80.0);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 25),
      child: Wrap(
        children: [
          SfRangeSlider(
            min: 0.0,
            max: 100.0,
            values: _values,
            interval: 20,
            showTicks: true,
            showLabels: true,
            enableTooltip: true,
            minorTicksPerInterval: 1,
            onChanged: (SfRangeValues values) {
              setState(() {
                _values = values;
              });
            },
          ),
          const SizedBox(height: 100),
        ],
      ),
    );
  }
}
```

Yet, I still get the error in my main app. I'll keep debugging and let you know if I find anything!

**Comment by PraveenGopalsamy** [comment]
Hi kartik1225,

We have tried to reproduce the reported scenario in SfSlider with version 19.4.47 but were unable to reproduce the mentioned null exception at our end. We have attached the sample which we tried for your reference. Kindly check the sample and still if you are facing issue in your side, please modify the given sample code along with replication procedure which will be helpful to reproduce at our side.

```
  double _value = 0.5;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SfSlider(
          value: _value,
          onChanged: (dynamic value) {},
        ),
      ),
    );
  }
```
Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi ahuang11,

Thank you for your update.

Please let us know if you need any further assistance in this.

Regards,
Praveen G.
