### ISSUE TITLE
[syncfusion_flutter_pdfviewer] 19.4.54-beta  Unhandled Exception: type 'PdfReferenceHolder' is not a subtype of type 'PdfArray?' in type cast

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-widgets#616]
I'm getting this error when I search for the word "jornal" in this PDF

https://www.riodasostras.rj.gov.br/wp-content/uploads/2022/02/1423.pdf

```console
 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'PdfReferenceHolder' is not a subtype of type 'PdfArray?' in type cast
E/flutter (23181): #0      FontStructure.getHexaDecimalString (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/font_structure.dar
    rt:4505:19)
E/flutter (23181): #1      FontStructure.decodeTextExtraction (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/font_structure.dart:2590:25)
E/flutter (23181): #2      ImageRenderer._renderTextElementWithLeading (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/image_renderer.dart:629:26)
E/flutter (23181): #3      ImageRenderer.renderAsImage (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/image_renderer.dart:373:17)
E/flutter (23181): #4      PdfTextExtractor._searchInBackground (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:523:18)
E/flutter (23181): #5      PdfTextExtractor._findTextFromRange (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:258:11)
E/flutter (23181): #6      PdfTextExtractor._findText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:214:16)
E/flutter (23181): #7      PdfTextExtractor.findText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:149:12)
E/flutter (23181): #8      SfPdfViewerState._handleControllerValueChange (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3188:44)
E/flutter (23181): #9      _ValueChangeNotifier.notifyPropertyChangedListeners (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:4367:15)
E/flutter (23181): #10     PdfViewerController.searchText (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:4252:5)
E/flutter (23181): #11     _JornalDetalhePageState.onSearch (package:riodasostrasapp/app/modules/jornal/pages/jornal_detalhe_page.dart:303:50)
E/flutter (23181): <asynchronous suspension>
E/flutter (23181):
```

```dart
// ignore_for_file: deprecated_member_use

import 'package:flutter/material.dart';
import 'package:flutter_modular/flutter_modular.dart';
import 'package:riodasostrasapp/app/modules/jornal/jornal_controller.dart';
import 'package:riodasostrasapp/app/shared/theme/style.dart';
import 'package:riodasostrasapp_core/riodasostrasapp_core.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

class JornalDetalhePage extends StatefulWidget {
  final Jornal jornal;

  const JornalDetalhePage({Key? key, required this.jornal}) : super(key: key);

  @override
  _JornalDetalhePageState createState() => _JornalDetalhePageState();
}

class _JornalDetalhePageState extends State<JornalDetalhePage> {
  final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();
  late PdfViewerController _pdfViewerController;
  late JornalController _jornalController;
  late PdfTextSearchResult _searchResult;
  TextEditingController textEditingController = TextEditingController();

  String? searchText;
  @override
  void initState() {
    _pdfViewerController = PdfViewerController();
    _jornalController = Modular.get<JornalController>();
    _searchResult = PdfTextSearchResult();

    searchText = _jornalController.searchString;
    if (searchText != null) {
      textEditingController.text = searchText!;
    }

    print('JornalDetalhePage searchText: $searchText');
    super.initState();
  }

  bool isLoading = true;

  void _showDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Resultado da pesquisa'),
          content: Text(
              'Não foram encontradas mais ocorrências. Deseja continuar a pesquisar desde o início?'),
          actions: <Widget>[
            FlatButton(
              onPressed: () {
                _searchResult.nextInstance();
                Navigator.of(context).pop();
                setState(() {});
              },
              child: Text('SIM'),
            ),
            FlatButton(
              onPressed: () {
                _searchResult.clear();
                Navigator.of(context).pop();
              },
              child: Text('NÂO'),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Container(
            padding: EdgeInsets.fromLTRB(5, 10, 0, 5),
            color: AppStyle.appBarDarkColor,
            child: SafeArea(
                child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    IconButton(
                      onPressed: () {
                        Modular.to.pop();
                      },
                      icon: Icon(
                        Icons.arrow_back,
                        color: Colors.white,
                      ),
                    ),
                    Expanded(
                      child: Container(
                        //alignment: Alignment.center,
                        margin: EdgeInsets.fromLTRB(0, 0, 10, 0),
                        height: 38,
                        decoration: BoxDecoration(
                            color: Colors.white,
                            borderRadius:
                                BorderRadius.all(Radius.circular(10))),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: <Widget>[
                            Expanded(
                              child: TextField(
                                textAlignVertical: TextAlignVertical.center,
                                controller: textEditingController,
                                keyboardType: TextInputType.text,
                                autocorrect: false,
                                onChanged: (v) {
                                  searchText = v;
                                },
                                decoration: InputDecoration(
                                  isDense: true,
                                  contentPadding:
                                      EdgeInsets.fromLTRB(16, 6, 0, 0),
                                  hintText: 'Buscar',
                                  border: InputBorder.none,
                                  hintStyle: TextStyle(
                                      color: Colors.grey, fontFamily: 'Roboto'),
                                ),
                              ),
                            ),
                            Container(
                              margin: EdgeInsets.fromLTRB(0, 0, 0, 0),
                              child: Row(
                                mainAxisSize: MainAxisSize.max,
                                children: [
                                  Visibility(
                                    visible: _searchResult.hasResult,
                                    child: IconButton(
                                      icon: Icon(
                                        Icons.clear,
                                      ),
                                      onPressed: () {
                                        setState(() {
                                          _searchResult.clear();
                                        });
                                      },
                                    ),
                                  ),
                                  IconButton(
                                    onPressed: () {
                                      if (!isLoading) onSearch();
                                    },
                                    icon: Icon(
                                      Icons.search,
                                    ),
                                  )
                                ],
                              ),
                            )
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
                //options
                Container(
                  padding: EdgeInsets.fromLTRB(10, 5, 0, 0),
                  child: Row(
                    mainAxisSize: MainAxisSize.max,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Container(
                        child: Text(
                          'Pag.: ${_pdfViewerController.pageNumber}/${_pdfViewerController.pageCount}',
                          style: TextStyle(color: Colors.white, fontSize: 10),
                        ),
                      ),

                      //zoom
                      Container(
                        margin: EdgeInsets.fromLTRB(0, 0, 0, 0),
                        child: Row(mainAxisSize: MainAxisSize.min, children: [
                          IconButton(
                              tooltip: 'Zoom +',
                              onPressed: () {
                                _pdfViewerController.zoomLevel++;
                              },
                              icon: Icon(
                                Icons.zoom_in,
                                color: Colors.white,
                              )),
                          IconButton(
                              tooltip: 'Zoom -',
                              onPressed: () {
                                _pdfViewerController.zoomLevel--;
                              },
                              icon: Icon(
                                Icons.zoom_out,
                                color: Colors.white,
                              )),
                        ]),
                      ),

                      //busca
                      if (_searchResult.hasResult)
                        Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Container(
                                child: Text(
                              'Result.: ${_searchResult.currentInstanceIndex}/${_searchResult.totalInstanceCount}',
                              style:
                                  TextStyle(color: Colors.white, fontSize: 11),
                            )),
                            IconButton(
                              icon: Icon(
                                Icons.navigate_before,
                                color: Colors.white,
                              ),
                              onPressed: () {
                                _searchResult.previousInstance();
                                setState(() {});
                              },
                            ),
                            IconButton(
                              icon: Icon(
                                Icons.navigate_next,
                                color: Colors.white,
                              ),
                              onPressed: () {
                                if (_searchResult.currentInstanceIndex ==
                                    _searchResult.totalInstanceCount) {
                                  _showDialog(context);
                                } else {
                                  _searchResult.nextInstance();
                                }
                                setState(() {});
                              },
                            ),
                          ],
                        )
                    ],
                  ),
                ),
              ],
            )),
          ),
          Expanded(
            child: Stack(
              children: [
                SfPdfViewer.network(
                  widget.jornal.link!,
                  onPageChanged: (details) {
                    //setState(() {});
                  },
                  onDocumentLoaded: (details) {
                    setState(() {
                      isLoading = false;
                    });

                    print('onDocumentLoaded $isLoading');

                    Future.delayed(Duration(milliseconds: 200), () {
                      if (widget.jornal.currentPage != null) {
                        _pdfViewerController
                            .jumpToPage(widget.jornal.currentPage!);
                        print('ir para ${widget.jornal.currentPage}');
                      }
                      onSearch();
                    });
                  },
                  initialZoomLevel: 1,
                  interactionMode: PdfInteractionMode.selection,
                  key: _pdfViewerKey,
                  controller: _pdfViewerController,
                ),
                if (isLoading)
                  Positioned.fill(
                    child: Container(
                      color: Color(0xAAdddddd),
                      child: Center(
                        child: CircularProgressIndicator(),
                      ),
                    ),
                  )
              ],
            ),
          ),
        ],
      ),
    );
  }

  Future<void> onSearch() async {
    if (searchText != null && searchText?.isNotEmpty == true) {
      if (!isLoading) {
        setState(() {
          isLoading = true;
          print('isLoading $isLoading');
        });
      }
      await Future.delayed(Duration(milliseconds: 100));

      _searchResult = await _pdfViewerController.searchText(searchText!);

      await Future.delayed(Duration(milliseconds: 100));
      setState(() {
        isLoading = false;
        print('isLoading $isLoading');
      });
    }
  }
}

```

**Comment by deepika134** [comment]
Hi Isaque Neves,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on March 8, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi Isaque Neves,

We have confirmed that the reported issue “Typecasting issue occurs while trying to search text in the specific PDF document” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on 15 March 2022. The status of this issue can be tracked using the following link, https://www.syncfusion.com/feedback/33259/typecasting-issue-occurs-while-trying-to-search-text-in-specific-pdf-document 

Regards,
Deepika Ravi.

**Comment by deepika134** [comment]
Hi Isaque Neves,

We have included the fix for this issue “Typecasting issue occurs while trying to search text in the specific PDF document” in our latest weekly NuGet release, so kindly upgrade to the latest version v19.4.56 to get the issue resolved.    
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.56-beta 

Regards,
Deepika Ravi
