### ISSUE TITLE
[syncfusion_flutter_xlsio] The `mergeCells` function is incomplete?

### ISSUE THREAD

**Issue by YowFung** [syncfusion/flutter-widgets#628]
My sample code:
```dart
final wb = Workbook();
final sheet = wb.worksheets.addWithName("Sheet");
final mergeCells = MergedCellCollection();
mergeCells.addCell(MergeCell()..x = 1..y = 1..width = 3..height = 1);
sheet.mergeCells = mergeCells;
File("output.xls").writeAsBytesSync(wb.saveAsStream);
wb.dispose();
```

Error log:
```txt
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field '_reference@20196584' has not been initialized.
#0      MergeCell._reference (package:syncfusion_flutter_xlsio/src/xlsio/merged_cells/merge_cells.dart)
#1      SerializeWorkbook._saveWorksheet.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_xlsio/src/xlsio/general/serialize_workbook.dart:377:46)
#2      XmlBuilder._insert (package:xml/src/xml/builder.dart:287:12)
#3      XmlBuilder.element (package:xml/src/xml/builder.dart:154:7)
#4      SerializeWorkbook._saveWorksheet.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_xlsio/src/xlsio/general/serialize_workbook.dart:376:21)
#5      XmlBuilder._insert (package:xml/src/xml/builder.dart:287:12)
#6      XmlBuilder.element (package:xml/src/xml/builder.dart:154:7)
#7      SerializeWorkbook._saveWorksheet.<anonymous closure> (package:syncfusion_flutter_xlsio/src/xlsio/general/serialize_workbook.dart:372:17)
#8      XmlBuilder._insert (package:xml/src/xml/builder.dart:287:12)
#9      XmlBuilder.element (package:xml/src/xml/builder.dart:154:7)
#10     SerializeWorkbook._saveWorksheet (package:syncfusion_flutter_xlsio/src/xlsio/general/serialize_workbook.dart:185:13)
#11     SerializeWorkbook._saveWorksheets (package:syncfusion_flutter_xlsio/src/xlsio/general/serialize_workbook.dart:152:7)
#12     SerializeWorkbook._saveInternal (package:syncfusion_flutter_xlsio/src/xlsio/general/serialize_workbook.dart:60:5)
#13     Workbook.saveAsStream (package:syncfusion_flutter_xlsio/src/xlsio/general/workbook.dart:6171:16)
```

And then I found the `MergeCell` class definition:
```dart
/// Represents merged cell.
class MergeCell {
  /// Represent merged cell reference.
  late String _reference;

  /// Represents left cell index value.
  late int x;

  /// Represents width of the merged cell.
  late int width;

  /// Represents top cell index value.
  late int y;

  /// Represents height of the merged cell.
  late int height;
}
```

How can I set value to the private field `_reference`?

**Comment by SivakumarRamya** [comment]
Hi YowFung,

Greetings from Syncfusion.

We can reproduce the issue and validate it currently. We will share the validation details in 1 business day, on March 14, 2022.

Regards,
Ramya.

**Comment by KonduruKeerthi** [comment]
Hi YowFung,

We appreciate your patience.

We have analyzed and found that the issue is with the usage of code snippet. We have modified it to overcome the issue. Please find the modified code snippet below.

**Code Snippet:**

final Workbook workbook = Workbook();
final Worksheet sheet = workbook.worksheets.addWithName('Sheet');

sheet.getRangeByName('A1:D2').merge();

final List<int> bytes = workbook.saveAsStream();
saveAsExcel(bytes, 'output.xlsx');
workbook.dispose();

Also, it is not possible to set merged cells collection. So, merged cells and all other properties along with _reference will be marked as obsolete in future release. Kindly try the modified code snippet and let us know if it helps.

Regards,
Keerthi.

**Comment by YowFung** [comment]
@KonduruKeerthi 
Nice! Thank you!
