### ISSUE TITLE
[syncfusion_datagrid] checkbox selection exception when deselect last row

### ISSUE THREAD

**Issue by squaregen** [syncfusion/flutter-widgets#744]
Hi,
when i deselect the last selected row with a checkbox column i get an exception.
```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      RowSelectionManager._updateCheckboxStateOnHeader (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:517:75)
#1      RowSelectionManager._removeSelection (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:319:7)
#2      RowSelectionManager._applySelection (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:188:11)
#3      RowSelectionManager._processSelection (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:584:5)
#4      RowSelectionManager.handleTap (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:554:7)
#5      DataCellBase.onTouchUp (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/generator.dart:104:12)
#6      handleSelectionFromCheckbox (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:2043:18)
#7      GridCheckboxRenderer.onInitializeDisplayWidget.<anonymous closure> (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/cell_renderers.dart:263:33)
#8      ToggleableStateMixin._handleTap (package:flutter/src/material/toggleable.dart:233:19)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#24     _invoke1 (dart:ui/hooks.dart:170:10)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#eec39
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(29.6, 289.6)
  finalLocalPosition: Offset(29.6, 30.6)
  button: 1
  sent tap down
====================================================================================================
```

This is a repo with a problem
https://github.com/squaregen/testdatagrid

1. Select a row
2. Deselect a row

In the version 20.1.52 this operation working well

This is my configuration:

```bash
flutter doctor -v
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Versione 10.0.19044.1706], locale it-IT)
    • Flutter version 3.0.0 at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\MilosL.MULTTECHSRL\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @squaregen,

We have checked your reported issue and logged this as a bug. We will include the changes in our upcoming weekly pub release which is scheduled to be rolled out on May 24, 2022. We will let you know once it gets rolled out. We appreciate your patience until then. You can follow up with the below feedback for further details, 

Feedback Link: https://www.syncfusion.com/feedback/35029/the-null-check-operator-used-on-a-null-value-exception-is-thrown-when-selecting 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @squaregen,

Thank you for your patience.
 
We are glad to inform you that the fix has been included in our weekly patch release. Please update the DataGrid package to the **20.1.57** version.

Please let us know if you need further assistance on this.

Regards,  
Tamilarasan

**Comment by squaregen** [comment]
It works!
Thank you very much
