### ISSUE TITLE
[syncfusion_datagrid 20.1.57] Exception when i deselect rows with controller and showCheckboxColumn is true

### ISSUE THREAD

**Issue by squaregen** [syncfusion/flutter-widgets#758]
Hi,
I have a datagrid with showCheckboxColumn=true.
When i deselect rows with controller 
```dart
gridController.selectedRows = [];
```
i get this exception:

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      RowSelectionManager._clearSelectedRows (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:336:52)
#1      RowSelectionManager.onSelectedRowsChanged (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:725:7)
#2      RowSelectionManager._handleSelectionPropertyChanged (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:869:9)
#3      handleSelectionPropertyChanged (package:syncfusion_flutter_datagrid/src/datagrid_widget/selection/selection_manager.dart:1957:25)
#4      SfDataGridState._handleSelectionPropertyChanged (package:syncfusion_flutter_datagrid/src/datagrid_widget/sfdatagrid.dart:2563:23)
#5      DataGridSourceChangeNotifier._notifyDataGridPropertyChangeListeners (package:syncfusion_flutter_datagrid/src/datagrid_widget/sfdatagrid.dart:3851:15)
#6      DataGridController.selectedRows= (package:syncfusion_flutter_datagrid/src/datagrid_widget/sfdatagrid.dart:3499:5)
#7      DataScreenState.build.<anonymous closure>.<anonymous closure> (package:testdatagrid/data_screen.dart:56:31)
#8      State.setState (package:flutter/src/widgets/framework.dart:1109:30)
#9      DataScreenState.build.<anonymous closure> (package:testdatagrid/data_screen.dart:53:9)
#10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:232:7)
#15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#31     _invoke1 (dart:ui/hooks.dart:170:10)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#ef999
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(1222.4, 642.4)
  finalLocalPosition: Offset(28.8, 32.0)
  button: 1
  sent tap down
====================================================================================================
```

This repo contains the problem:
https://github.com/squaregen/testdatagrid

1. Select one or more rows
2. Click on clear button to deselect

In the version 20.1.52 this operation working well

This is my configuration:

```powershell
flutter doctor -v
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Versione 10.0.19044.1706], locale it-IT)
    • Flutter version 3.0.1 at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\MilosL.MULTTECHSRL\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @squaregen,

We have checked your reported issue and logged this as a bug. We will include the changes in our upcoming weekly pub release which is scheduled to be rolled out on May 31, 2022. We will let you know once it gets rolled out. We appreciate your patience until then. You can follow up with the below feedback for further details, 

Feedback Link:  https://www.syncfusion.com/feedback/35168/the-null-check-operator-used-on-a-null-value-exception-is-thrown-when-deselecting 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @squaregen,

Thank you for your patience.
 
We are glad to inform you that the fix has been included in our weekly patch release. Please update the DataGrid package to the **20.1.58** version.

Please let us know if you need further assistance on this.

Regards,  
Tamilarasan

**Comment by squaregen** [comment]
Thank you very much,
it works
