### ISSUE TITLE
error on DateTimeCategoryAxis when we have one register

### ISSUE THREAD

**Issue by robertoltrocha** [syncfusion/flutter-widgets#785]
Hi,

I have had this issue when I have only one record (one month)
data:
{data: 2022-06-01T00:00:00, manutencao: 1000.0, taxa: 1700.0, combustivel: 500.0, total: 3200.0, mediatotal: 3200.0}

![WhatsApp Image 2022-06-09 at 23 09 28](https://user-images.githubusercontent.com/30963205/172976906-44f923d2-1c93-4e65-a955-68efb3e7dd4a.jpeg)

```

======== Exception caught by widgets library =======================================================
The following FormatException was thrown building LayoutBuilder:
Invalid radix-10 number (at character 1)
06/2022
^

T```
he relevant error-causing widget was: 
  SfCartesianChart SfCartesianChart:file:///C:/Users/
When the exception was thrown, this was the stack: 
#0      int._handleFormatError (dart:core-patch/integers_patch.dart:131:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:142:16)
#2      int._parse (dart:core-patch/integers_patch.dart:103:12)
#3      int.parse (dart:core-patch/integers_patch.dart:65:12)
#4      DateTimeCategoryAxisDetails.getFormattedLabel (package:syncfusion_flutter_charts/src/chart/axis/datetime_category_axis.dart:707:57)
#5      DateTimeCategoryAxisRenderer.generateVisibleLabels (package:syncfusion_flutter_charts/src/chart/axis/datetime_category_axis.dart:552:36)
#6      DateTimeCategoryAxisDetails.calculateRangeAndInterval (package:syncfusion_flutter_charts/src/chart/axis/datetime_category_axis.dart:667:22)
#7      ChartAxisPanel.measureAxesBounds (package:syncfusion_flutter_charts/src/chart/axis/axis_panel.dart:214:21)
```

with two month I had no issue
{data: 2022-05-01T00:00:00, manutencao: 0.0, taxa: 0.0, combustivel: 600.0, total: 600.0, mediatotal: 1900.0}, {data: 2022-06-01T00:00:00, manutencao: 1000.0, taxa: 1700.0, combustivel: 500.0, total: 3200.0, mediatotal: 1900.0}

![WhatsApp Image 2022-06-09 at 23 17 00](https://user-images.githubusercontent.com/30963205/172977254-4ed44eae-23ca-4b21-a55e-f4a21b259fb0.jpeg)

```
SfCartesianChart(
                                    isTransposed: true,
                                    primaryYAxis: NumericAxis(numberFormat: NumberFormat.simpleCurrency()),
                                    primaryXAxis: DateTimeCategoryAxis(
                                        dateFormat: DateFormat.yM(),
                                        isInversed: true,
                                        labelPlacement: LabelPlacement.betweenTicks),
                                    // Chart title
                                    title: ChartTitle(text: 'Custo Mensal'),
                                    // Enable legend
                                    legend: Legend(isVisible: true),
                                    // Enable tooltip
                                    tooltipBehavior: TooltipBehavior(enable: true),
                                    series: <CartesianSeries<EstatisticaCusto, DateTime>>[
                                        ColumnSeries<EstatisticaCusto, DateTime>(
                                            name: "Taxa",
                                            enableTooltip: true,
                                            dataSource: listEstatisticaCusto,
                                            xValueMapper: (EstatisticaCusto sales, _) => sales.data,
                                            yValueMapper: (EstatisticaCusto sales, _) => sales.taxa,
                                            // Enable data label
                                            dataLabelSettings: const DataLabelSettings(isVisible: false)),
                                        ColumnSeries<EstatisticaCusto, DateTime>(
                                            name: "Manutenção",
                                            dataSource: listEstatisticaCusto,
                                            enableTooltip: true,
                                            xValueMapper: (EstatisticaCusto sales, _) => sales.data,
                                            yValueMapper: (EstatisticaCusto sales, _) => sales.manutencao,
                                            // Enable data label
                                            dataLabelSettings: const DataLabelSettings(isVisible: false)),
                                        ColumnSeries<EstatisticaCusto, DateTime>(
                                            name: "Combustível",
                                            dataSource: listEstatisticaCusto,
                                            enableTooltip: true,
                                            xValueMapper: (EstatisticaCusto sales, _) => sales.data,
                                            yValueMapper: (EstatisticaCusto sales, _) => sales.combustivel,
                                            // Enable data label
                                            dataLabelSettings: const DataLabelSettings(isVisible: false)),
                                        ColumnSeries<EstatisticaCusto, DateTime>(
                                            name: "Total",
                                            dataSource: listEstatisticaCusto,
                                            enableTooltip: true,
                                            xValueMapper: (EstatisticaCusto sales, _) => sales.data,
                                            yValueMapper: (EstatisticaCusto sales, _) => sales.total,
                                            // Enable data label
                                            dataLabelSettings: const DataLabelSettings(isVisible: false)),
                                        LineSeries<EstatisticaCusto, DateTime>(
                                            name: "Média",
                                            dataSource: listEstatisticaCusto,
                                            enableTooltip: true,
                                            xValueMapper: (EstatisticaCusto sales, _) => sales.data,
                                            yValueMapper: (EstatisticaCusto sales, _) => sales.mediatotal,
                                            // Enable data label
                                            dataLabelSettings: const DataLabelSettings(isVisible: false))
                                      ]))
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @robertoltrocha,

Thanks for your patience. The reported issue regarding getting exceptions while having one data in the [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html) has been fixed and rolled out in our weekly patch release. To avoid this issue, please upgrade the chart package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.60+1 

Regards,
Yuvaraj.

**Comment by robertoltrocha** [comment]
thanks
perfect!
