### ISSUE TITLE
[syncfusion_flutter_datagrid_export][flutter_web] Error: Unexpected null value

### ISSUE THREAD

**Issue by hmbenhaim** [syncfusion/flutter-widgets#788]
Hi, 
I'm using SfDataGrid and I wanted to use the data grid export lib

I followed the steps as shown in the example.
I'm getting the error when I'm calling   ``` final Workbook workbook = dataGridKey.currentState!.exportToExcelWorkbook();```

I'm getting the following error:

```
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:35000/dart_sdk.js:5080:11)
    at Object.nullCheck (http://localhost:35000/dart_sdk.js:5399:30)
    at export_to_excel.DataGridToExcelConverter.new.getCellValue (http://localhost:35000/packages/syncfusion_flutter_datagrid_export/src/export_to_excel.dart.lib.js:348:28)
    at export_to_excel.DataGridToExcelConverter.new.exportRow (http://localhost:35000/packages/syncfusion_flutter_datagrid_export/src/export_to_excel.dart.lib.js:286:28)
    at export_to_excel.DataGridToExcelConverter.new.exportRows (http://localhost:35000/packages/syncfusion_flutter_datagrid_export/src/export_to_excel.dart.lib.js:279:16)
    at export_to_excel.DataGridToExcelConverter.new.exportToExcelWorksheet (http://localhost:35000/packages/syncfusion_flutter_datagrid_export/src/export_to_excel.dart.lib.js:365:12)
    at export_to_excel.DataGridToExcelConverter.new.exportToExcelWorkbook (http://localhost:35000/packages/syncfusion_flutter_datagrid_export/src/export_to_excel.dart.lib.js:373:12)
    at Object.DataGridExcelExportExtensions$124exportToExcelWorkbook [as DataGridExcelExportExtensions|exportToExcelWorkbook]
    (http://localhost:35000/packages/syncfusion_flutter_datagrid_export/src/export_to_excel.dart.lib.js:625:22)
    at table_content.TableContentState.new._exportDataGridToExcel (http://localhost:35000/packages/my_package/src/widgets/save_data_hadler.dart.lib.js:15841:94)
    at _exportDataGridToExcel.next (<anonymous>)
    at runBody (http://localhost:35000/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:35000/dart_sdk.js:40691:7)
    at [_exportDataGridToExcel] (http://localhost:35000/packages/my_package/src/widgets/save_data_hadler.dart.lib.js:15838:20)
    at [_handleTap] (http://localhost:35000/packages/flutter/src/material/icon_button.dart.lib.js:42254:31)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:35000/packages/flutter/src/gestures/recognizer.dart.lib.js:198:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:35000/packages/flutter/src/gestures/tap.dart.lib.js:411:42)
    at [_checkUp] (http://localhost:35000/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:35000/packages/flutter/src/gestures/tap.dart.lib.js:166:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:35000/packages/flutter/src/gestures/recognizer.dart.lib.js:444:16)
    at [_dispatch] (http://localhost:35000/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
    at http://localhost:35000/packages/flutter/src/gestures/pointer_router.dart.lib.js:112:26
    at LinkedMap.new.forEach (http://localhost:35000/dart_sdk.js:27745:11)
    at [_dispatchEventToRoutes] (http://localhost:35000/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:29)
    at pointer_router.PointerRouter.new.route (http://localhost:35000/packages/flutter/src/gestures/pointer_router.dart.lib.js:105:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:35000/packages/flutter/src/gestures/binding.dart.lib.js:367:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:35000/packages/flutter/src/gestures/binding.dart.lib.js:355:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:35000/packages/flutter/src/rendering/layer.dart.lib.js:5440:13)
    at [_handlePointerEventImmediately] (http://localhost:35000/packages/flutter/src/gestures/binding.dart.lib.js:331:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:35000/packages/flutter/src/gestures/binding.dart.lib.js:305:43)
    at [_flushPointerEventQueue] (http://localhost:35000/packages/flutter/src/gestures/binding.dart.lib.js:295:14)
    at [_handlePointerDataPacket] (http://localhost:35000/packages/flutter/src/gestures/binding.dart.lib.js:286:54)
    at Object.invoke1 (http://localhost:35000/dart_sdk.js:191747:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:35000/dart_sdk.js:171943:15)
    at [_onPointerData] (http://localhost:35000/dart_sdk.js:172879:49)
    at http://localhost:35000/dart_sdk.js:173317:28
    at http://localhost:35000/dart_sdk.js:173273:16
    at loggedHandler (http://localhost:35000/dart_sdk.js:172978:11)
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @hmbenhaim,

Greetings from Syncfusion.

Based on the provided information, we are unable to reproduce your reported issue. It's working fine at our end. We have prepared a sample for your reference. Please check the following sample

**Sample Link**:  https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample1450269327 

In the **getCellValue** method, we are mapping the cell values based on the column names mentioned in the **GridColumn.columnName** and **DataGridCell.columnName** in the **buildRow** method. We suspect that you are setting different name. Please make sure whether you set the same column name on both methods.

**Code Snippet:**
```dart
GridColumn(
          columnName: 'id',
          label: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child: const Text(
                'ID',
              ))),

void buildDataGridRow(List<Employee> employeeData) {
    dataGridRow = employeeData.map<DataGridRow>((employee) {
      return DataGridRow(cells: [
        DataGridCell<int>(columnName: 'id', value: employee.id),
        DataGridCell<String>(columnName: 'name', value: employee.name),
        DataGridCell<String>(
            columnName: 'designation', value: employee.designation),
        DataGridCell<int>(columnName: 'salary', value: employee.salary),
      ]);
    }).toList();
  }

```

We hope this helps. Please let us know if you need further assistance.

Regards,
Tamilarasan

**Comment by hmbenhaim** [comment]
Hi, thank you
my issue really was that the column name didn't match in the column and the cell because I added columns manually at the start of the table and I didn't put the same name, now it is working for me.
