### ISSUE TITLE
DoughnutSeriesRendererExtension is not a subtype of type CartesianSeriesRenderer

### ISSUE THREAD

**Issue by mescarpenter** [syncfusion/flutter-widgets#814]
I using chart library but when app call chart this throw an error:

pubspec.yaml:
`syncfusion_flutter_charts: ^20.2.36`

Function:
```
Widget _chart(){
    return SfCartesianChart(
        primaryXAxis: CategoryAxis(),
        primaryYAxis: NumericAxis(minimum: 0, maximum: 40, interval: 10),
        tooltipBehavior: TooltipBehavior(enable: true),
        series: <ChartSeries<_ChartData, String>>[
          DoughnutSeries<_ChartData, String>(
            startAngle: 0,
            endAngle: 180,
            dataSource: [
              _ChartData('CHN', 12),
              _ChartData('GER', 15),
              _ChartData('RUS', 30),
              _ChartData('BRZ', 6.4),
              _ChartData('IND', 14)
            ],
            xValueMapper: (_ChartData data, _) => data.x,
            yValueMapper: (_ChartData data, _) => data.y,
            name: 'Gold',
          ),
        ],
    );
  }
  ```

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building Container:
type 'DoughnutSeriesRendererExtension' is not a subtype of type 'CartesianSeriesRenderer'

The relevant error-causing widget was: 
  Container Container:file:///C:/Repositoris/hub%20OS/hub_buildings/lib/views/projects/v_project_floors.dart:76:13
When the exception was thrown, this was the stack: 
#0      SfCartesianChartState._createAndUpdateSeriesRenderer (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:1626:11)
#1      SfCartesianChartState.initState (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:1331:5)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4942:57)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#21     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#27     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#28     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#33     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#48     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#53     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#55     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#60     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#64     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#68     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#77     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#82     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#85     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#87     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#92     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#93     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#94     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#95     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#99     _invoke (dart:ui/hooks.dart:151:10)
#100    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#101    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
E/flutter (17550): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
E/flutter (17550): #0      StatefulElement.state (package:flutter/src/widgets/framework.dart:4926:44)
E/flutter (17550): #1      Navigator.of (package:flutter/src/widgets/navigator.dart:2542:47)
E/flutter (17550): #2      bProjects.downloadProject (package:hub_buildings/bloc/projects/bProjects.dart:78:15)
E/flutter (17550): <asynchronous suspension>
E/flutter (17550): 

```

Flutter doctor -v:
```
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Versi¢n 10.0.19044.1766], locale es-ES)
    • Flutter version 3.0.4 at C:\SDKs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (6 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Windows\AppData\Local\Android\sdk
    • Platform android-32, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (4 available)
    • SM G986B (mobile) • RFCN90KAGYX • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Versi¢n 10.0.19044.1766]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 103.0.1264.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

´´´

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @mescarpenter,

Greetings from Syncfusion. We have checked the code snippet attached to the query and found that your declares the doughnut series inside the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), but doughnut series needs to be declared inside the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html). Because it is related to circular chart type. To resolve the issue please declare the doughnut series in the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html) like in the below code snippet.

Code snippet:
```dart
SfCircularChart(
  tooltipBehavior: TooltipBehavior(enable: true),
  series: <CircularSeries<_ChartData, String>>[
    DoughnutSeries<_ChartData, String>(
      startAngle: 0,
      endAngle: 180,
      dataSource: [
        _ChartData('CHN', 12),
        _ChartData('GER', 15),
        _ChartData('RUS', 30),
        _ChartData('BRZ', 6.4),
        _ChartData('IND', 14)
      ],
      xValueMapper: (_ChartData data, _) => data.x,
      yValueMapper: (_ChartData data, _) => data.y,
      name: 'Gold',
    ),
  ],
)
```

Regards,
Yuvaraj.

**Comment by leduchung** [comment]
thanks @Yuvaraj-Gajaraj. In this case, please kindly update the documentation in the code section: https://www.syncfusion.com/flutter-widgets/flutter-charts/chart-types/doughnut-chart.

**Comment by LavanyaGowtham2021** [comment]
Hi leduchung,



Thanks. Currently, we are working on this, and we will modify and update it in our upcoming release.



Regards,

Lavanya A.
