### ISSUE TITLE
[syncfusion_flutter_pdfviewer ] Null check operator used on a null value Exception

### ISSUE THREAD

**Issue by devalp-pro** [syncfusion/flutter-widgets#935]
Steps to reproduce

Different URLs load in a single pdf viewer using a simple set state method.
Put 2 buttons for changing the pdf load URL in the same view. The first time loads perfectly both pdf. But when switching back it from one to another after the first load of both pdf it gives this exception.

My Sample code is to switch different URL's in the same pdf viewer instance.

```
if ((loadEngFileUrl != null && loadEngFileUrl?.isNotEmpty == true) || (loadChnFileUrl != null && loadChnFileUrl?.isNotEmpty == true))
Expanded(
    child: SfPdfViewer.network(
      (loadEngFileUrl != null && loadEngFileUrl?.isNotEmpty == true) ? loadEngFileUrl! : loadChnFileUrl!,
      key: pdfViewerState,
      onDocumentLoadFailed: (details) {
        setState(() {
          isFileFound = false;
        });
      },
      enableDoubleTapZooming: true,
      pageLayoutMode: PdfPageLayoutMode.single,
      enableTextSelection: false,
      interactionMode: PdfInteractionMode.pan,
      controller: (loadEngFileUrl != null && loadEngFileUrl?.isNotEmpty == true) ? engPdfViewerController : chnPdfViewerController,
    ),
  )
```

```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building SinglePageView-[LabeledGlobalKey<SinglePageViewState>#b38a3](dirty, dependencies: [MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#e91b5]], state: SinglePageViewState#e6e9a):
Null check operator used on a null value

The relevant error-causing widget was: 
  SfPdfViewer-[LabeledGlobalKey<SfPdfViewerState>#16780] SfPdfViewer:file:///D:/Projects/Flutter/The_Dvrc/MobileApp/lib/screens/investor_form/investor_bank_form_instruction_page.dart:247:36
When the exception was thrown, this was the stack: 
#0      SinglePageViewState.build (package:syncfusion_flutter_pdfviewer/src/control/single_page_view.dart:320:56)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#13     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#15     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#21     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#28     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#32     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#34     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#35     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#39     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#43     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#47     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#51     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#53     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#54     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#58     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#61     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#66     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#68     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#72     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#77     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#83     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#88     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#90     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#93     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#95     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#99     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#107    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#110    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#112    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#116    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#119    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#121    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#126    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#127    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#128    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#129    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#130    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#131    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#132    _invoke (dart:ui/hooks.dart:148:13)
#133    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#134    _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================
```

**Comment by deepika134** [comment]
Hi Team,

We can replicate the reported issue on our side. We are checking on this and will update the further details on October 27,2022.

Regards,
Deepika Ravi

**Comment by bambinoua** [comment]
@devalp-pro I have as suggestion to use [spoiler](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287) for hiding big data.

**Comment by deepika134** [comment]
Hi @devalp-pro ,

We have included the fix for the reported issue in our latest weekly NuGet release, so kindly upgrade to the latest version v20.3.52 to get the issue resolved. 

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.3.52

Regards,
Deepika Ravi
