### ISSUE TITLE
[syncfusion_flutter_charts] RangeError (index): Invalid value: Not in inclusive range when using Trackball with FastLineSeries

### ISSUE THREAD

**Issue by mivoligo** [syncfusion/flutter-widgets#951]
Checking on `Flutter 3.3.6` and `syncfusion_flutter_charts: ^20.3.52`

This issue appears only when using FastLineSeries. If I use `LineSeries` instead, the issue goes away.

When moving mouse on the right part of the screen where is the blue chart only, I get following error repeatedly:
```
====================================================================================================

======== Exception caught by gesture library =======================================================
The following RangeError was thrown while dispatching a pointer event:
RangeError (index): Invalid value: Not in inclusive range 0..8672: 8717

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      TrackballRenderingDetails._getLeastX (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:1341:23)
#2      TrackballRenderingDetails._validateNearestXValue (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:1281:20)
#3      TrackballRenderingDetails.generateAllPoints (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:1101:7)
#4      TrackballBehavior.show (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:465:37)
#5      TrackballBehaviorRenderer.onEnter (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:624:52)
#6      ContainerArea._performMouseHover (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:3943:18)
#7      ContainerArea.build.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2367:39)
#8      RenderMouseRegion.handleEvent (package:flutter/src/rendering/proxy_box.dart:3254:22)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#15     _invoke1 (dart:ui/hooks.dart:167:13)
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
Event: PointerHoverEvent#819bb(position: Offset(1111.3, 394.6))
  position: Offset(1111.3, 394.6)
Target: RenderMouseRegion#87c21
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1152.0, h=592.0)
  size: Size(1152.0, 592.0)
  behavior: opaque
  listeners: hover, exit
====================================================================================================

```
Video below:

[range_error.webm](https://user-images.githubusercontent.com/1629120/199021962-a37ca1e8-15c5-4949-8ed2-a015315309dc.webm)

Here's the code I used:
```dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: ChartView(),
    );
  }
}

class ChartView extends StatelessWidget {
  const ChartView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      margin: const EdgeInsets.all(64),
      trackballBehavior: TrackballBehavior(
        enable: true,
        activationMode: ActivationMode.singleTap,
      ),
      series: <ChartSeries>[
        FastLineSeries(
          dataSource: bigData,
          xValueMapper: (data, _) => data.x,
          yValueMapper: (data, _) => data.y,
          animationDuration: 0,
        ),
        FastLineSeries(
          dataSource: largeData,
          xValueMapper: (data, _) => data.x,
          yValueMapper: (data, _) => data.y,
          animationDuration: 0,
        ),
      ],
    );
  }
}

Random random = Random();

final largeData = List.generate(
  9000,
  (index) => Point(index, random.nextDouble() * 7 + 60),
);
final bigData = List.generate(
  10000,
  (index) => Point(index, random.nextDouble() * 7),
);
```

**Comment by timonaldenhoff** [comment]
Is there any update yet?

**Comment by jongkb** [comment]
I'm facing a similar issue as above with Flutter 3.7.6 and syncfusion_flutter_charts 20.4.52.

**Comment by LokeshPalani** [comment]
We were able to replicate the reported issue and logged a bug report in our feedback portal. We will fix it and include the necessary changes in the first weekly patch release after the Volume 2 main release, which is expected to be available by the end of this month. We will update you once the release has been rolled out and appreciate your patience until then. You can also track the status of the bug through the feedback link provided below.

Feedback Link -  https://www.syncfusion.com/feedback/44517/range-error-exception-thrown-while-using-multiple-series-with-different-data

**Comment by sfHariHaraSudhan** [comment]
Hi @mivoligo,

The reported issue regarding **Range error exception thrown while using multiple series with different data source length** has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/22.1.36

Regards,
Hari Hara Sudhan. K.
