### ISSUE TITLE
SfSlider AnimationController.reverse() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by Sureya** [syncfusion/flutter-widgets#982]
```yaml
syncfusion_flutter_sliders: ^20.3.57
syncfusion_flutter_core: ^20.3.57
```

While moving the slider value getting the following error, any help on this would be really appreciated

```
AnimationController.reverse() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
Failed assertion: line 493 pos 7: '_ticker != null'

When the exception was thrown, this was the stack: 
#2      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:493:7)
#3      _RenderSlider._endInteraction (package:syncfusion_flutter_sliders/src/slider.dart:2053:32)
#4      _RenderSlider._onDragEnd (package:syncfusion_flutter_sliders/src/slider.dart:1989:5)
#5      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:521:47)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#7      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:521:5)
#8      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:426:9)
#9      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:446:9)
#10     DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:435:5)
#11     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:354:7)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#24     _invoke1 (dart:ui/hooks.dart:167:13)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 2 frames from class _AssertionError)
Handler: "onEnd"
Recognizer: HorizontalDragGestureRecognizer#f238a
  start behavior: start

```

slider code

```dart
SfSliderTheme(
                    data: SfSliderThemeData(
                      thumbRadius: 13,
                      thumbColor: customTopazColor,
                      activeLabelStyle: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: customTopazColor,
                      ),
                      inactiveLabelStyle: TextStyle(
                        fontSize: 15,
                        fontWeight: FontWeight.normal,
                        color: customElectricBlueColor,
                      ),
                      activeTrackColor: customElectricBlueColor,
                      inactiveTrackColor: Colors.grey.withOpacity(0.6),
                    ),
                    child: SfSlider(
                      min: 10,
                      max: 50.0,
                      stepSize: 5,
                      interval: 10,
                      showTicks: true,
                      showLabels: true,
                      enableTooltip: true,
                      showDividers: true,
                      minorTicksPerInterval: 1,
                      value: _value,
                      onChanged: (dynamic newValue){
                        setState(() {
                          _value = newValue;
                        });
                      },
                    ),
                  )
```

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue regarding the **slider widget throwing an assertion exception when moving the slider thumb** issue has been fixed and rolled out in our weekly patch release. To avoid this issue please upgrade the Slider package to the latest version mentioned below.



Version: https://pub.dev/packages/syncfusion_flutter_sliders/versions/20.3.60
